/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authProvider 
 * @param createdAt 
 * @param email 
 * @param id 
 * @param isActive 
 * @param isAdmin 
 * @param mustChangePassword 
 * @param username 
 * @param displayName 
 * @param lastLoginAt 
 */
@Serializable

data class AdminUserResponse (

    @SerialName(value = "auth_provider")
    val authProvider: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "email")
    val email: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean,

    @SerialName(value = "is_admin")
    val isAdmin: kotlin.Boolean,

    @SerialName(value = "must_change_password")
    val mustChangePassword: kotlin.Boolean,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    @Contextual @SerialName(value = "last_login_at")
    val lastLoginAt: java.time.OffsetDateTime? = null

) {


}

