/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.FacetsResponse
import com.artifactkeeper.client.models.PaginationInfo
import com.artifactkeeper.client.models.SearchResultItem

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param facets 
 * @param items 
 * @param pagination 
 */
@Serializable

data class AdvancedSearchResponse (

    @SerialName(value = "facets")
    val facets: FacetsResponse,

    @SerialName(value = "items")
    val items: kotlin.collections.List<SearchResultItem>,

    @SerialName(value = "pagination")
    val pagination: PaginationInfo

) {


}

