/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Alert state for a service.
 *
 * @param consecutiveFailures 
 * @param currentStatus 
 * @param serviceName 
 * @param updatedAt 
 * @param lastAlertSentAt 
 * @param suppressedUntil 
 */
@Serializable

data class AlertState (

    @SerialName(value = "consecutive_failures")
    val consecutiveFailures: kotlin.Int,

    @SerialName(value = "current_status")
    val currentStatus: kotlin.String,

    @SerialName(value = "service_name")
    val serviceName: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "last_alert_sent_at")
    val lastAlertSentAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "suppressed_until")
    val suppressedUntil: java.time.OffsetDateTime? = null

) {


}

