/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param name 
 * @param scopes 
 * @param tokenPrefix 
 * @param expiresAt 
 * @param lastUsedAt 
 */
@Serializable

data class ApiTokenResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "token_prefix")
    val tokenPrefix: kotlin.String,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_used_at")
    val lastUsedAt: java.time.OffsetDateTime? = null

) {


}

