/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId Artifact ID to promote
 * @param sourceRepository Source staging repository key
 * @param targetRepository Target release repository key
 * @param notes Free-text justification
 * @param skipPolicyCheck Skip policy evaluation
 */
@Serializable

data class ApprovalRequest (

    /* Artifact ID to promote */
    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    /* Source staging repository key */
    @SerialName(value = "source_repository")
    val sourceRepository: kotlin.String,

    /* Target release repository key */
    @SerialName(value = "target_repository")
    val targetRepository: kotlin.String,

    /* Free-text justification */
    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    /* Skip policy evaluation */
    @SerialName(value = "skip_policy_check")
    val skipPolicyCheck: kotlin.Boolean? = null

) {


}

