/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param perPage 
 * @param sourceRepository 
 * @param status 
 */
@Serializable

data class ApprovalHistoryQuery (

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "source_repository")
    val sourceRepository: kotlin.String? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null

) {


}

