/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param format 
 * @param metadata 
 * @param properties 
 */
@Serializable

data class ArtifactMetadataResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "format")
    val format: kotlin.String,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlinx.serialization.json.JsonElement?,

    @Contextual @SerialName(value = "properties")
    val properties: kotlinx.serialization.json.JsonElement?

) {


}

