/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checksumSha256 
 * @param contentType 
 * @param createdAt 
 * @param downloadCount 
 * @param id 
 * @param name 
 * @param path 
 * @param repositoryKey 
 * @param sizeBytes 
 * @param metadata 
 * @param version 
 */
@Serializable

data class ArtifactResponse (

    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

