/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param downloadCount 
 * @param firstDownloaded 
 * @param lastDownloaded 
 */
@Serializable

data class ArtifactStatsResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @Contextual @SerialName(value = "first_downloaded")
    val firstDownloaded: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_downloaded")
    val lastDownloaded: java.time.OffsetDateTime? = null

) {


}

