/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checksumSha256 
 * @param contentType 
 * @param createdAt 
 * @param downloadCount 
 * @param id 
 * @param name 
 * @param path 
 * @param repositoryKey 
 * @param sizeBytes 
 * @param cacheCachedAt When the proxy cache entry for this artifact was last written. Only populated for Remote (proxy) repositories whose proxy service is configured AND that have a cache-metadata blob for this path. None for Local / Virtual / Staging repos and for Remote repos whose cache hasn't been populated yet (e.g. an artifact that exists as a DB row from a direct upload but has never been fetched through the proxy). (#1541)
 * @param cacheExpiresAt When the proxy cache entry for this artifact will expire and be re-validated against upstream. Same gating as `cache_cached_at`. (#1541)
 * @param metadata 
 * @param version 
 */
@Serializable

data class ArtifactResponse (

    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    /* When the proxy cache entry for this artifact was last written. Only populated for Remote (proxy) repositories whose proxy service is configured AND that have a cache-metadata blob for this path. None for Local / Virtual / Staging repos and for Remote repos whose cache hasn't been populated yet (e.g. an artifact that exists as a DB row from a direct upload but has never been fetched through the proxy). (#1541) */
    @Contextual @SerialName(value = "cache_cached_at")
    val cacheCachedAt: java.time.OffsetDateTime? = null,

    /* When the proxy cache entry for this artifact will expire and be re-validated against upstream. Same gating as `cache_cached_at`. (#1541) */
    @Contextual @SerialName(value = "cache_expires_at")
    val cacheExpiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlin.Any? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

