/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param excludePaths 
 * @param includePaths 
 * @param matchTags Tag selectors (AND semantics). Key = tag key, value = required tag value. Empty value means \"key must exist with any value\".
 * @param maxAgeDays 
 * @param maxSizeBytes 
 */
@Serializable

data class ArtifactFilterSchema (

    @SerialName(value = "exclude_paths")
    val excludePaths: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "include_paths")
    val includePaths: kotlin.collections.List<kotlin.String>? = null,

    /* Tag selectors (AND semantics). Key = tag key, value = required tag value. Empty value means \"key must exist with any value\". */
    @SerialName(value = "match_tags")
    val matchTags: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "max_age_days")
    val maxAgeDays: kotlin.Int? = null,

    @SerialName(value = "max_size_bytes")
    val maxSizeBytes: kotlin.Long? = null

) {


}

