/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.RepositoryAssessment

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockers 
 * @param estimatedDurationSeconds 
 * @param groupsCount 
 * @param jobId 
 * @param permissionsCount 
 * @param repositories 
 * @param status 
 * @param totalArtifacts 
 * @param totalSizeBytes 
 * @param usersCount 
 * @param warnings 
 */
@Serializable

data class AssessmentResult (

    @SerialName(value = "blockers")
    val blockers: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "estimated_duration_seconds")
    val estimatedDurationSeconds: kotlin.Long,

    @SerialName(value = "groups_count")
    val groupsCount: kotlin.Long,

    @Contextual @SerialName(value = "job_id")
    val jobId: java.util.UUID,

    @SerialName(value = "permissions_count")
    val permissionsCount: kotlin.Long,

    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<RepositoryAssessment>,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "total_artifacts")
    val totalArtifacts: kotlin.Long,

    @SerialName(value = "total_size_bytes")
    val totalSizeBytes: kotlin.Long,

    @SerialName(value = "users_count")
    val usersCount: kotlin.Long,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {


}

