/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param repositoryId 
 * @param replicationMode 
 * @param replicationSchedule 
 * @param syncEnabled 
 */
@Serializable

data class AssignRepoRequest (

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String? = null,

    @SerialName(value = "replication_schedule")
    val replicationSchedule: kotlin.String? = null,

    @SerialName(value = "sync_enabled")
    val syncEnabled: kotlin.Boolean? = null

) {


}

