/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param replicationFilter Optional JSONB filter constraining which artifacts in the repository get replicated. Shape: `{\"include_patterns\": [\"^v\\\\d+\\\\.\"], \"exclude_patterns\": [\".*-SNAPSHOT$\"]}`. Null/absent means replicate everything.
 * @param repositoryId 
 * @param replicationMode 
 * @param replicationSchedule 
 * @param syncEnabled 
 */
@Serializable

data class AssignRepoRequest (

    /* Optional JSONB filter constraining which artifacts in the repository get replicated. Shape: `{\"include_patterns\": [\"^v\\\\d+\\\\.\"], \"exclude_patterns\": [\".*-SNAPSHOT$\"]}`. Null/absent means replicate everything. */
    @Contextual @SerialName(value = "replication_filter")
    val replicationFilter: kotlin.Any,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String? = null,

    @SerialName(value = "replication_schedule")
    val replicationSchedule: kotlin.String? = null,

    @SerialName(value = "sync_enabled")
    val syncEnabled: kotlin.Boolean? = null

) {


}

