/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Authentication provider availability.
 *
 * @param ldapEnabled Whether an LDAP directory is configured.
 * @param oidcEnabled Whether an OIDC provider is configured.
 * @param ssoEnabled Whether SAML SSO is configured (derived from the SSO admin settings in the DB, but for this endpoint we report whether the OIDC issuer is set as a proxy).
 */
@Serializable

data class AuthConfig (

    /* Whether an LDAP directory is configured. */
    @SerialName(value = "ldap_enabled")
    val ldapEnabled: kotlin.Boolean,

    /* Whether an OIDC provider is configured. */
    @SerialName(value = "oidc_enabled")
    val oidcEnabled: kotlin.Boolean,

    /* Whether SAML SSO is configured (derived from the SSO admin settings in the DB, but for this endpoint we report whether the OIDC issuer is set as a proxy). */
    @SerialName(value = "sso_enabled")
    val ssoEnabled: kotlin.Boolean

) {


}

