/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactCount 
 * @param createdAt 
 * @param id 
 * @param sizeBytes 
 * @param status 
 * @param type 
 * @param completedAt 
 * @param createdBy 
 * @param errorMessage 
 * @param startedAt 
 * @param storagePath 
 */
@Serializable

data class BackupResponse (

    @SerialName(value = "artifact_count")
    val artifactCount: kotlin.Long,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID? = null,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "storage_path")
    val storagePath: kotlin.String? = null

) {


}

