/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.BuildModule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param name 
 * @param number 
 * @param status 
 * @param updatedAt 
 * @param agent 
 * @param artifactCount 
 * @param durationMs 
 * @param finishedAt 
 * @param metadata 
 * @param modules 
 * @param startedAt 
 * @param vcsBranch 
 * @param vcsMessage 
 * @param vcsRevision 
 * @param vcsUrl 
 */
@Serializable

data class BuildResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "number")
    val number: kotlin.Int,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "agent")
    val agent: kotlin.String? = null,

    @SerialName(value = "artifact_count")
    val artifactCount: kotlin.Int? = null,

    @SerialName(value = "duration_ms")
    val durationMs: kotlin.Long? = null,

    @Contextual @SerialName(value = "finished_at")
    val finishedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "modules")
    val modules: kotlin.collections.List<BuildModule>? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "vcs_branch")
    val vcsBranch: kotlin.String? = null,

    @SerialName(value = "vcs_message")
    val vcsMessage: kotlin.String? = null,

    @SerialName(value = "vcs_revision")
    val vcsRevision: kotlin.String? = null,

    @SerialName(value = "vcs_url")
    val vcsUrl: kotlin.String? = null

) {


}

