/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param newChecksum 
 * @param newSizeBytes 
 * @param oldChecksum 
 * @param oldSizeBytes 
 * @param path 
 */
@Serializable

data class BuildArtifactDiff (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "new_checksum")
    val newChecksum: kotlin.String,

    @SerialName(value = "new_size_bytes")
    val newSizeBytes: kotlin.Long,

    @SerialName(value = "old_checksum")
    val oldChecksum: kotlin.String,

    @SerialName(value = "old_size_bytes")
    val oldSizeBytes: kotlin.Long,

    @SerialName(value = "path")
    val path: kotlin.String

) {


}

