/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.BuildArtifact
import com.artifactkeeper.client.models.BuildArtifactDiff

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param added 
 * @param buildA 
 * @param buildB 
 * @param modified 
 * @param removed 
 */
@Serializable

data class BuildDiffResponse (

    @SerialName(value = "added")
    val added: kotlin.collections.List<BuildArtifact>,

    @Contextual @SerialName(value = "build_a")
    val buildA: java.util.UUID,

    @Contextual @SerialName(value = "build_b")
    val buildB: java.util.UUID,

    @SerialName(value = "modified")
    val modified: kotlin.collections.List<BuildArtifactDiff>,

    @SerialName(value = "removed")
    val removed: kotlin.collections.List<BuildArtifact>

) {


}

