/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param buildId 
 * @param checksumSha256 
 * @param createdAt 
 * @param id 
 * @param name 
 * @param path 
 * @param sizeBytes 
 * @param moduleName 
 */
@Serializable

data class BuildArtifactResponse (

    @Contextual @SerialName(value = "build_id")
    val buildId: java.util.UUID,

    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "module_name")
    val moduleName: kotlin.String? = null

) {


}

