/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.ArtifactEvalEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param failed 
 * @param passed 
 * @param results 
 * @param ruleId 
 * @param ruleName 
 * @param totalArtifacts 
 */
@Serializable

data class BulkEvaluationResponse (

    @SerialName(value = "failed")
    val failed: kotlin.Int,

    @SerialName(value = "passed")
    val passed: kotlin.Int,

    @SerialName(value = "results")
    val results: kotlin.collections.List<ArtifactEvalEntry>,

    @Contextual @SerialName(value = "rule_id")
    val ruleId: java.util.UUID,

    @SerialName(value = "rule_name")
    val ruleName: kotlin.String,

    @SerialName(value = "total_artifacts")
    val totalArtifacts: kotlin.Int

) {


}

