/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.PromotionResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param failed 
 * @param promoted 
 * @param results 
 * @param total 
 */
@Serializable

data class BulkPromotionResponse (

    @SerialName(value = "failed")
    val failed: kotlin.Int,

    @SerialName(value = "promoted")
    val promoted: kotlin.Int,

    @SerialName(value = "results")
    val results: kotlin.collections.List<PromotionResponse>,

    @SerialName(value = "total")
    val total: kotlin.Int

) {


}

