/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactIds 
 * @param targetRepository 
 * @param notes 
 * @param skipPolicyCheck 
 */
@Serializable

data class BulkPromoteRequest (

    @SerialName(value = "artifact_ids")
    val artifactIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "target_repository")
    val targetRepository: kotlin.String,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @SerialName(value = "skip_policy_check")
    val skipPolicyCheck: kotlin.Boolean? = null

) {


}

