/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cacheTtlSeconds 
 * @param repositoryKey 
 */
@Serializable

data class CacheTtlResponse (

    @SerialName(value = "cache_ttl_seconds")
    val cacheTtlSeconds: kotlin.Long,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String

) {


}

