/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checkType 
 * @param issuesCount 
 * @param status 
 * @param completedAt 
 * @param passed 
 * @param score 
 */
@Serializable

data class CheckSummary (

    @SerialName(value = "check_type")
    val checkType: kotlin.String,

    @SerialName(value = "issues_count")
    val issuesCount: kotlin.Int,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "passed")
    val passed: kotlin.Boolean? = null,

    @SerialName(value = "score")
    val score: kotlin.Int? = null

) {


}

