/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param checkType 
 * @param createdAt 
 * @param criticalCount 
 * @param highCount 
 * @param id 
 * @param infoCount 
 * @param issuesCount 
 * @param lowCount 
 * @param mediumCount 
 * @param repositoryId 
 * @param status 
 * @param checkerVersion 
 * @param completedAt 
 * @param details 
 * @param errorMessage 
 * @param passed 
 * @param score 
 * @param startedAt 
 */
@Serializable

data class CheckResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "check_type")
    val checkType: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "critical_count")
    val criticalCount: kotlin.Int,

    @SerialName(value = "high_count")
    val highCount: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "info_count")
    val infoCount: kotlin.Int,

    @SerialName(value = "issues_count")
    val issuesCount: kotlin.Int,

    @SerialName(value = "low_count")
    val lowCount: kotlin.Int,

    @SerialName(value = "medium_count")
    val mediumCount: kotlin.Int,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "checker_version")
    val checkerVersion: kotlin.String? = null,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "details")
    val details: kotlin.Any? = null,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String? = null,

    @SerialName(value = "passed")
    val passed: kotlin.Boolean? = null,

    @SerialName(value = "score")
    val score: kotlin.Int? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null

) {


}

