/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param byteLength 
 * @param byteOffset 
 * @param checksum 
 * @param chunkIndex 
 * @param status 
 * @param sourcePeerId 
 */
@Serializable

data class ChunkEntry (

    @SerialName(value = "byte_length")
    val byteLength: kotlin.Int,

    @SerialName(value = "byte_offset")
    val byteOffset: kotlin.Long,

    @SerialName(value = "checksum")
    val checksum: kotlin.String,

    @SerialName(value = "chunk_index")
    val chunkIndex: kotlin.Int,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "source_peer_id")
    val sourcePeerId: java.util.UUID? = null

) {


}

