/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bytesReceived 
 * @param chunkIndex 
 * @param chunksCompleted 
 * @param chunksRemaining 
 */
@Serializable

data class ChunkResponse (

    @SerialName(value = "bytes_received")
    val bytesReceived: kotlin.Long,

    @SerialName(value = "chunk_index")
    val chunkIndex: kotlin.Int,

    @SerialName(value = "chunks_completed")
    val chunksCompleted: kotlin.Int,

    @SerialName(value = "chunks_remaining")
    val chunksRemaining: kotlin.Int

) {


}

