/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.ChunkEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param chunks 
 * @param sessionId 
 */
@Serializable

data class ChunkManifestResponse (

    @SerialName(value = "chunks")
    val chunks: kotlin.collections.List<ChunkEntry>,

    @Contextual @SerialName(value = "session_id")
    val sessionId: java.util.UUID

) {


}

