/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param availableChunks 
 * @param chunkBitmap 
 * @param peerInstanceId 
 * @param totalChunks 
 */
@Serializable

data class ChunkAvailabilityResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "available_chunks")
    val availableChunks: kotlin.Int,

    @SerialName(value = "chunk_bitmap")
    val chunkBitmap: kotlin.collections.List<kotlin.Int>,

    @Contextual @SerialName(value = "peer_instance_id")
    val peerInstanceId: java.util.UUID,

    @SerialName(value = "total_chunks")
    val totalChunks: kotlin.Int

) {


}

