/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param cleanupAuditLogs 
 * @param cleanupOldBackups 
 * @param cleanupStalePeers 
 * @param cleanupStaleUploads 
 */
@Serializable

data class CleanupRequest (

    @SerialName(value = "cleanup_audit_logs")
    val cleanupAuditLogs: kotlin.Boolean? = null,

    @SerialName(value = "cleanup_old_backups")
    val cleanupOldBackups: kotlin.Boolean? = null,

    @SerialName(value = "cleanup_stale_peers")
    val cleanupStalePeers: kotlin.Boolean? = null,

    @SerialName(value = "cleanup_stale_uploads")
    val cleanupStaleUploads: kotlin.Boolean? = null

) {


}

