/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param licenses 
 * @param name 
 * @param sbomId 
 * @param author 
 * @param componentType 
 * @param cpe 
 * @param md5 
 * @param purl 
 * @param sha1 
 * @param sha256 
 * @param supplier 
 * @param version 
 */
@Serializable

data class ComponentResponse (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "licenses")
    val licenses: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "sbom_id")
    val sbomId: java.util.UUID,

    @SerialName(value = "author")
    val author: kotlin.String? = null,

    @SerialName(value = "component_type")
    val componentType: kotlin.String? = null,

    @SerialName(value = "cpe")
    val cpe: kotlin.String? = null,

    @SerialName(value = "md5")
    val md5: kotlin.String? = null,

    @SerialName(value = "purl")
    val purl: kotlin.String? = null,

    @SerialName(value = "sha1")
    val sha1: kotlin.String? = null,

    @SerialName(value = "sha256")
    val sha256: kotlin.String? = null,

    @SerialName(value = "supplier")
    val supplier: kotlin.String? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

