/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checksum 
 * @param sourcePeerId 
 */
@Serializable

data class CompleteChunkBody (

    @SerialName(value = "checksum")
    val checksum: kotlin.String,

    @Contextual @SerialName(value = "source_peer_id")
    val sourcePeerId: java.util.UUID? = null

) {


}

