/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param password 
 * @param token 
 * @param username 
 */
@Serializable

data class ConnectionCredentials (

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "token")
    val token: kotlin.String? = null,

    @SerialName(value = "username")
    val username: kotlin.String? = null

) {


}

