/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param message 
 * @param success 
 * @param artifactoryVersion 
 * @param licenseType 
 */
@Serializable

data class ConnectionTestResult (

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "artifactory_version")
    val artifactoryVersion: kotlin.String? = null,

    @SerialName(value = "license_type")
    val licenseType: kotlin.String? = null

) {


}

