/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param config 
 * @param sourceConnectionId 
 * @param jobType 
 */
@Serializable

data class CreateMigrationRequest (

    @Contextual @SerialName(value = "config")
    val config: kotlin.Any,

    @Contextual @SerialName(value = "source_connection_id")
    val sourceConnectionId: java.util.UUID,

    @SerialName(value = "job_type")
    val jobType: kotlin.String? = null

) {


}

