/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param chunkCount 
 * @param chunkSize 
 * @param expiresAt 
 * @param sessionId 
 */
@Serializable

data class CreateSessionResponse (

    @SerialName(value = "chunk_count")
    val chunkCount: kotlin.Int,

    @SerialName(value = "chunk_size")
    val chunkSize: kotlin.Int,

    @SerialName(value = "expires_at")
    val expiresAt: kotlin.String,

    @Contextual @SerialName(value = "session_id")
    val sessionId: java.util.UUID

) {


}

