/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param actions 
 * @param principalId 
 * @param principalType 
 * @param targetId 
 * @param targetType 
 */
@Serializable

data class CreatePermissionRequest (

    @SerialName(value = "actions")
    val actions: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "principal_id")
    val principalId: java.util.UUID,

    @SerialName(value = "principal_type")
    val principalType: kotlin.String,

    @Contextual @SerialName(value = "target_id")
    val targetId: java.util.UUID,

    @SerialName(value = "target_type")
    val targetType: kotlin.String

) {


}

