/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param certificate 
 * @param entityId 
 * @param name 
 * @param ssoUrl 
 * @param adminGroup 
 * @param attributeMapping 
 * @param isEnabled 
 * @param nameIdFormat 
 * @param requireSignedAssertions 
 * @param signRequests 
 * @param sloUrl 
 * @param spEntityId 
 */
@Serializable

data class CreateSamlConfigRequest (

    @SerialName(value = "certificate")
    val certificate: kotlin.String,

    @SerialName(value = "entity_id")
    val entityId: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "sso_url")
    val ssoUrl: kotlin.String,

    @SerialName(value = "admin_group")
    val adminGroup: kotlin.String? = null,

    @Contextual @SerialName(value = "attribute_mapping")
    val attributeMapping: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @SerialName(value = "name_id_format")
    val nameIdFormat: kotlin.String? = null,

    @SerialName(value = "require_signed_assertions")
    val requireSignedAssertions: kotlin.Boolean? = null,

    @SerialName(value = "sign_requests")
    val signRequests: kotlin.Boolean? = null,

    @SerialName(value = "slo_url")
    val sloUrl: kotlin.String? = null,

    @SerialName(value = "sp_entity_id")
    val spEntityId: kotlin.String? = null

) {


}

