/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param purpose 
 * @param resourcePath 
 */
@Serializable

data class CreateTicketRequest (

    @SerialName(value = "purpose")
    val purpose: kotlin.String,

    @SerialName(value = "resource_path")
    val resourcePath: kotlin.String? = null

) {


}

