/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactPath Path within the repository (e.g. \"images/vm.ova\")
 * @param checksumSha256 Expected SHA256 checksum of the complete file
 * @param repositoryKey Repository key (e.g. \"my-repo\")
 * @param totalSize Total file size in bytes
 * @param artifactMetadata 
 * @param artifactMetadataFormat Source artifact metadata format for peer replication.
 * @param artifactMetadataProperties 
 * @param artifactName Artifact name to persist when the upload completes.  Optional for regular client uploads. Peer replication sets this from the source artifact row so chunked replication preserves metadata.
 * @param artifactVersion Artifact version to persist when the upload completes.  Optional for regular client uploads. Peer replication sets this from the source artifact row so chunked replication preserves metadata.
 * @param chunkSize Chunk size in bytes (default 8 MB, range 1 MB - 256 MB)
 * @param contentType MIME content type (default \"application/octet-stream\")
 * @param packageDescription Source package description for peer replication.
 * @param packageMetadata 
 */
@Serializable

data class CreateSessionRequest (

    /* Path within the repository (e.g. \"images/vm.ova\") */
    @SerialName(value = "artifact_path")
    val artifactPath: kotlin.String,

    /* Expected SHA256 checksum of the complete file */
    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    /* Repository key (e.g. \"my-repo\") */
    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    /* Total file size in bytes */
    @SerialName(value = "total_size")
    val totalSize: kotlin.Long,

    @Contextual @SerialName(value = "artifact_metadata")
    val artifactMetadata: kotlin.Any? = null,

    /* Source artifact metadata format for peer replication. */
    @SerialName(value = "artifact_metadata_format")
    val artifactMetadataFormat: kotlin.String? = null,

    @Contextual @SerialName(value = "artifact_metadata_properties")
    val artifactMetadataProperties: kotlin.Any? = null,

    /* Artifact name to persist when the upload completes.  Optional for regular client uploads. Peer replication sets this from the source artifact row so chunked replication preserves metadata. */
    @SerialName(value = "artifact_name")
    val artifactName: kotlin.String? = null,

    /* Artifact version to persist when the upload completes.  Optional for regular client uploads. Peer replication sets this from the source artifact row so chunked replication preserves metadata. */
    @SerialName(value = "artifact_version")
    val artifactVersion: kotlin.String? = null,

    /* Chunk size in bytes (default 8 MB, range 1 MB - 256 MB) */
    @SerialName(value = "chunk_size")
    val chunkSize: kotlin.Int? = null,

    /* MIME content type (default \"application/octet-stream\") */
    @SerialName(value = "content_type")
    val contentType: kotlin.String? = null,

    /* Source package description for peer replication. */
    @SerialName(value = "package_description")
    val packageDescription: kotlin.String? = null,

    @Contextual @SerialName(value = "package_metadata")
    val packageMetadata: kotlin.Any? = null

) {


}

