/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.UserResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param user 
 * @param generatedPassword 
 */
@Serializable

data class CreateUserResponse (

    @SerialName(value = "user")
    val user: UserResponse,

    @SerialName(value = "generated_password")
    val generatedPassword: kotlin.String? = null

) {


}

