/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param format 
 * @param key 
 * @param name 
 * @param repoType 
 * @param description 
 * @param isPublic 
 * @param quotaBytes 
 * @param upstreamUrl 
 */
@Serializable

data class CreateRepositoryRequest (

    @SerialName(value = "format")
    val format: kotlin.String,

    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "repo_type")
    val repoType: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "is_public")
    val isPublic: kotlin.Boolean? = null,

    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long? = null,

    @SerialName(value = "upstream_url")
    val upstreamUrl: kotlin.String? = null

) {


}

