/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param username 
 * @param displayName 
 * @param isAdmin 
 * @param password 
 */
@Serializable

data class CreateUserRequest (

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    @SerialName(value = "is_admin")
    val isAdmin: kotlin.Boolean? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null

) {


}

