/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param action 
 * @param description 
 * @param enforceOnDownload 
 * @param enforceOnPromotion 
 * @param maxCriticalIssues 
 * @param maxHighIssues 
 * @param maxMediumIssues 
 * @param minHealthScore 
 * @param minMetadataScore 
 * @param minQualityScore 
 * @param minSecurityScore 
 * @param repositoryId 
 * @param requiredChecks 
 */
@Serializable

data class CreateGateRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "enforce_on_download")
    val enforceOnDownload: kotlin.Boolean? = null,

    @SerialName(value = "enforce_on_promotion")
    val enforceOnPromotion: kotlin.Boolean? = null,

    @SerialName(value = "max_critical_issues")
    val maxCriticalIssues: kotlin.Int? = null,

    @SerialName(value = "max_high_issues")
    val maxHighIssues: kotlin.Int? = null,

    @SerialName(value = "max_medium_issues")
    val maxMediumIssues: kotlin.Int? = null,

    @SerialName(value = "min_health_score")
    val minHealthScore: kotlin.Int? = null,

    @SerialName(value = "min_metadata_score")
    val minMetadataScore: kotlin.Int? = null,

    @SerialName(value = "min_quality_score")
    val minQualityScore: kotlin.Int? = null,

    @SerialName(value = "min_security_score")
    val minSecurityScore: kotlin.Int? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null,

    @SerialName(value = "required_checks")
    val requiredChecks: kotlin.collections.List<kotlin.String>? = null

) {


}

