/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.ConnectionCredentials

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authType 
 * @param credentials 
 * @param name 
 * @param url 
 * @param sourceType Source registry type: \"artifactory\" (default) or \"nexus\"
 */
@Serializable

data class CreateConnectionRequest (

    @SerialName(value = "auth_type")
    val authType: kotlin.String,

    @SerialName(value = "credentials")
    val credentials: ConnectionCredentials,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    /* Source registry type: \"artifactory\" (default) or \"nexus\" */
    @SerialName(value = "source_type")
    val sourceType: kotlin.String? = null

) {


}

