/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param sourceRepoId 
 * @param targetRepoId 
 * @param allowedLicenses 
 * @param autoPromote 
 * @param isEnabled 
 * @param maxArtifactAgeDays 
 * @param maxCveSeverity 
 * @param minHealthScore 
 * @param minStagingHours 
 * @param requireSignature 
 */
@Serializable

data class CreateRuleRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "source_repo_id")
    val sourceRepoId: java.util.UUID,

    @Contextual @SerialName(value = "target_repo_id")
    val targetRepoId: java.util.UUID,

    @SerialName(value = "allowed_licenses")
    val allowedLicenses: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "auto_promote")
    val autoPromote: kotlin.Boolean? = null,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @SerialName(value = "max_artifact_age_days")
    val maxArtifactAgeDays: kotlin.Int? = null,

    @SerialName(value = "max_cve_severity")
    val maxCveSeverity: kotlin.String? = null,

    @SerialName(value = "min_health_score")
    val minHealthScore: kotlin.Int? = null,

    @SerialName(value = "min_staging_hours")
    val minStagingHours: kotlin.Int? = null,

    @SerialName(value = "require_signature")
    val requireSignature: kotlin.Boolean? = null

) {


}

