/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param scopes 
 * @param description 
 * @param expiresInDays 
 * @param repoSelector Dynamic repository selector (match by labels, formats, name pattern). Mutually exclusive with `repository_ids`. When set, matched repos are resolved at auth time so new repos that match the selector are picked up automatically.
 * @param repositoryIds Explicit repository IDs to restrict access to. Mutually exclusive with `repo_selector`.
 */
@Serializable

data class CreateTokenRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "expires_in_days")
    val expiresInDays: kotlin.Long? = null,

    /* Dynamic repository selector (match by labels, formats, name pattern). Mutually exclusive with `repository_ids`. When set, matched repos are resolved at auth time so new repos that match the selector are picked up automatically. */
    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlin.Any? = null,

    /* Explicit repository IDs to restrict access to. Mutually exclusive with `repo_selector`. */
    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<@Contextual java.util.UUID>? = null

) {


}

