/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockOnFail 
 * @param blockUnscanned 
 * @param maxSeverity 
 * @param name 
 * @param repositoryId 
 */
@Serializable

data class CreatePolicyRequest (

    @SerialName(value = "block_on_fail")
    val blockOnFail: kotlin.Boolean,

    @SerialName(value = "block_unscanned")
    val blockUnscanned: kotlin.Boolean,

    @SerialName(value = "max_severity")
    val maxSeverity: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

