/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param events 
 * @param name 
 * @param url 
 * @param headers 
 * @param repositoryId 
 * @param secret 
 */
@Serializable

data class CreateWebhookRequest (

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @Contextual @SerialName(value = "headers")
    val headers: kotlinx.serialization.json.JsonElement? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null,

    @SerialName(value = "secret")
    val secret: kotlin.String? = null

) {


}

