/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param repoKey 
 * @param priority 
 */
@Serializable

data class CreateVirtualMemberInput (

    @SerialName(value = "repo_key")
    val repoKey: kotlin.String,

    @SerialName(value = "priority")
    val priority: kotlin.Int? = null

) {


}

