/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param buildNumber 
 * @param metadata 
 * @param name 
 * @param agent 
 * @param startedAt 
 * @param vcsBranch 
 * @param vcsMessage 
 * @param vcsRevision 
 * @param vcsUrl 
 */
@Serializable

data class CreateBuildRequest (

    @SerialName(value = "build_number")
    val buildNumber: kotlin.Int,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "agent")
    val agent: kotlin.String? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "vcs_branch")
    val vcsBranch: kotlin.String? = null,

    @SerialName(value = "vcs_message")
    val vcsMessage: kotlin.String? = null,

    @SerialName(value = "vcs_revision")
    val vcsRevision: kotlin.String? = null,

    @SerialName(value = "vcs_url")
    val vcsUrl: kotlin.String? = null

) {


}

