/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactPath Path within the repository (e.g. \"images/vm.ova\")
 * @param checksumSha256 Expected SHA256 checksum of the complete file
 * @param repositoryKey Repository key (e.g. \"my-repo\")
 * @param totalSize Total file size in bytes
 * @param chunkSize Chunk size in bytes (default 8 MB, range 1 MB - 256 MB)
 * @param contentType MIME content type (default \"application/octet-stream\")
 */
@Serializable

data class CreateSessionRequest (

    /* Path within the repository (e.g. \"images/vm.ova\") */
    @SerialName(value = "artifact_path")
    val artifactPath: kotlin.String,

    /* Expected SHA256 checksum of the complete file */
    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    /* Repository key (e.g. \"my-repo\") */
    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    /* Total file size in bytes */
    @SerialName(value = "total_size")
    val totalSize: kotlin.Long,

    /* Chunk size in bytes (default 8 MB, range 1 MB - 256 MB) */
    @SerialName(value = "chunk_size")
    val chunkSize: kotlin.Int? = null,

    /* MIME content type (default \"application/octet-stream\") */
    @SerialName(value = "content_type")
    val contentType: kotlin.String? = null

) {


}

