/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request to create an access token scoped to a repository.
 *
 * @param name Display name for the token.
 * @param scopes Permission scopes for the token.
 * @param description Optional human-readable description.
 * @param expiresInDays Number of days until the token expires (1-365). Omit for no expiration.
 */
@Serializable

data class CreateRepoTokenRequest (

    /* Display name for the token. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* Permission scopes for the token. */
    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    /* Optional human-readable description. */
    @SerialName(value = "description")
    val description: kotlin.String? = null,

    /* Number of days until the token expires (1-365). Omit for no expiration. */
    @SerialName(value = "expires_in_days")
    val expiresInDays: kotlin.Long? = null

) {


}

