/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Create API token request
 *
 * @param name 
 * @param scopes 
 * @param expiresInDays 
 */
@Serializable

data class CreateApiTokenRequest (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "expires_in_days")
    val expiresInDays: kotlin.Long? = null

) {


}

