/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response returned when a repository token is created. The `token` field contains the plaintext value and is only shown once.
 *
 * @param id 
 * @param name 
 * @param repositoryKey 
 * @param token The full token value (only returned at creation time).
 */
@Serializable

data class CreateRepoTokenResponse (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    /* The full token value (only returned at creation time). */
    @SerialName(value = "token")
    val token: kotlin.String

) {


}

