/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param artifactFilter 
 * @param description 
 * @param enabled 
 * @param filter Convenience glob filter (e.g. `\"*.tar.gz\"`). When set, it is folded into `artifact_filter.include_paths` so only matching artifact paths are eligible for sync. Ignored if `artifact_filter.include_paths` is already provided.
 * @param peerSelector 
 * @param precedence 
 * @param priority 
 * @param replicationMode 
 * @param repoSelector 
 */
@Serializable

data class CreateSyncPolicyPayload (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "artifact_filter")
    val artifactFilter: kotlin.Any? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Convenience glob filter (e.g. `\"*.tar.gz\"`). When set, it is folded into `artifact_filter.include_paths` so only matching artifact paths are eligible for sync. Ignored if `artifact_filter.include_paths` is already provided. */
    @SerialName(value = "filter")
    val filter: kotlin.String? = null,

    @Contextual @SerialName(value = "peer_selector")
    val peerSelector: kotlin.Any? = null,

    @SerialName(value = "precedence")
    val precedence: kotlin.Int? = null,

    @SerialName(value = "priority")
    val priority: kotlin.Int? = null,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String? = null,

    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlin.Any? = null

) {


}

