/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param eventTypes Event-type tokens to listen for. Must be drawn from `VALID_EVENT_TYPES`.
 * @param recipients Email addresses to deliver matching events to. Bounded length; see `MAX_RECIPIENTS_PER_SUBSCRIPTION` for the operator-facing limit.
 * @param enabled 
 */
@Serializable

data class CreateEmailSubscriptionRequest (

    /* Event-type tokens to listen for. Must be drawn from `VALID_EVENT_TYPES`. */
    @SerialName(value = "event_types")
    val eventTypes: kotlin.collections.List<kotlin.String>,

    /* Email addresses to deliver matching events to. Bounded length; see `MAX_RECIPIENTS_PER_SUBSCRIPTION` for the operator-facing limit. */
    @SerialName(value = "recipients")
    val recipients: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null

) {


}

