/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param repositoryIds 
 * @param type 
 */
@Serializable

data class CreateBackupRequest (

    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<@Contextual java.util.UUID>? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null

) {


}

