/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CVE history entry for tracking vulnerability timeline.
 *
 * @param artifactId 
 * @param createdAt 
 * @param cveId 
 * @param firstDetectedAt 
 * @param id 
 * @param lastDetectedAt 
 * @param status 
 * @param updatedAt 
 * @param acknowledgedAt 
 * @param acknowledgedBy 
 * @param acknowledgedReason 
 * @param affectedComponent 
 * @param affectedVersion 
 * @param componentId 
 * @param cvePublishedAt 
 * @param cvssScore 
 * @param fixedVersion 
 * @param sbomId 
 * @param scanResultId 
 * @param severity 
 */
@Serializable

data class CveHistoryEntry (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "cve_id")
    val cveId: kotlin.String,

    @Contextual @SerialName(value = "first_detected_at")
    val firstDetectedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "last_detected_at")
    val lastDetectedAt: java.time.OffsetDateTime,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "acknowledged_at")
    val acknowledgedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "acknowledged_by")
    val acknowledgedBy: java.util.UUID? = null,

    @SerialName(value = "acknowledged_reason")
    val acknowledgedReason: kotlin.String? = null,

    @SerialName(value = "affected_component")
    val affectedComponent: kotlin.String? = null,

    @SerialName(value = "affected_version")
    val affectedVersion: kotlin.String? = null,

    @Contextual @SerialName(value = "component_id")
    val componentId: java.util.UUID? = null,

    @Contextual @SerialName(value = "cve_published_at")
    val cvePublishedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "cvss_score")
    val cvssScore: kotlin.Double? = null,

    @SerialName(value = "fixed_version")
    val fixedVersion: kotlin.String? = null,

    @Contextual @SerialName(value = "sbom_id")
    val sbomId: java.util.UUID? = null,

    @Contextual @SerialName(value = "scan_result_id")
    val scanResultId: java.util.UUID? = null,

    @SerialName(value = "severity")
    val severity: kotlin.String? = null

) {


}

