/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * CVE status for tracking.
 *
 * Values: OPEN,FIXED,ACKNOWLEDGED,FALSE_POSITIVE
 */
@Serializable
enum class CveStatus(val value: kotlin.String) {

    @SerialName(value = "open")
    OPEN("open"),

    @SerialName(value = "fixed")
    FIXED("fixed"),

    @SerialName(value = "acknowledged")
    ACKNOWLEDGED("acknowledged"),

    @SerialName(value = "false_positive")
    FALSE_POSITIVE("false_positive");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CveStatus) "$data" else null

        /**
         * Returns a valid [CveStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CveStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

