/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.CveTimelineEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CVE trends summary.
 *
 * @param acknowledgedCves 
 * @param criticalCount 
 * @param fixedCves 
 * @param highCount 
 * @param lowCount 
 * @param mediumCount 
 * @param openCves 
 * @param timeline 
 * @param totalCves 
 * @param avgDaysToFix 
 */
@Serializable

data class CveTrends (

    @SerialName(value = "acknowledged_cves")
    val acknowledgedCves: kotlin.Long,

    @SerialName(value = "critical_count")
    val criticalCount: kotlin.Long,

    @SerialName(value = "fixed_cves")
    val fixedCves: kotlin.Long,

    @SerialName(value = "high_count")
    val highCount: kotlin.Long,

    @SerialName(value = "low_count")
    val lowCount: kotlin.Long,

    @SerialName(value = "medium_count")
    val mediumCount: kotlin.Long,

    @SerialName(value = "open_cves")
    val openCves: kotlin.Long,

    @SerialName(value = "timeline")
    val timeline: kotlin.collections.List<CveTimelineEntry>,

    @SerialName(value = "total_cves")
    val totalCves: kotlin.Long,

    @SerialName(value = "avg_days_to_fix")
    val avgDaysToFix: kotlin.Double? = null

) {


}

