/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.CveStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CVE timeline entry for trending.
 *
 * @param affectedComponent 
 * @param cveId 
 * @param daysExposed 
 * @param firstDetectedAt 
 * @param severity 
 * @param status 
 * @param cvePublishedAt 
 */
@Serializable

data class CveTimelineEntry (

    @SerialName(value = "affected_component")
    val affectedComponent: kotlin.String,

    @SerialName(value = "cve_id")
    val cveId: kotlin.String,

    @SerialName(value = "days_exposed")
    val daysExposed: kotlin.Long,

    @Contextual @SerialName(value = "first_detected_at")
    val firstDetectedAt: java.time.OffsetDateTime,

    @SerialName(value = "severity")
    val severity: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: CveStatus,

    @Contextual @SerialName(value = "cve_published_at")
    val cvePublishedAt: java.time.OffsetDateTime? = null

) {


}

