/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.CveTimelineEntry

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * CVE trends summary.  #1446: the security-tests `cve-history` suite probes the trends body for any of `total`, `count`, `critical`, or `high` to confirm the response carries aggregate counts (PR #1385 fixed `cve-history` but the trends shape was not aligned). The original field set (`total_cves`, `critical_count`, ...) is retained for openapi consumers; the bare `total`/`critical`/`high`/`medium`/`low` aliases are added alongside so both shape contracts are satisfied without breaking existing clients. `#[serde(default)]` keeps deserialization working when the alias fields are absent (older payloads, tests that build the struct via field init).
 *
 * @param acknowledgedCves 
 * @param criticalCount 
 * @param fixedCves 
 * @param highCount 
 * @param lowCount 
 * @param mediumCount 
 * @param openCves 
 * @param timeline 
 * @param totalCves 
 * @param avgDaysToFix 
 * @param critical Alias of `critical_count` (#1446).
 * @param high Alias of `high_count` (#1446).
 * @param low Alias of `low_count` (#1446).
 * @param medium Alias of `medium_count` (#1446).
 * @param total Alias of `total_cves` (#1446).
 */
@Serializable

data class CveTrends (

    @SerialName(value = "acknowledged_cves")
    val acknowledgedCves: kotlin.Long,

    @SerialName(value = "critical_count")
    val criticalCount: kotlin.Long,

    @SerialName(value = "fixed_cves")
    val fixedCves: kotlin.Long,

    @SerialName(value = "high_count")
    val highCount: kotlin.Long,

    @SerialName(value = "low_count")
    val lowCount: kotlin.Long,

    @SerialName(value = "medium_count")
    val mediumCount: kotlin.Long,

    @SerialName(value = "open_cves")
    val openCves: kotlin.Long,

    @SerialName(value = "timeline")
    val timeline: kotlin.collections.List<CveTimelineEntry>,

    @SerialName(value = "total_cves")
    val totalCves: kotlin.Long,

    @SerialName(value = "avg_days_to_fix")
    val avgDaysToFix: kotlin.Double? = null,

    /* Alias of `critical_count` (#1446). */
    @SerialName(value = "critical")
    val critical: kotlin.Long? = null,

    /* Alias of `high_count` (#1446). */
    @SerialName(value = "high")
    val high: kotlin.Long? = null,

    /* Alias of `low_count` (#1446). */
    @SerialName(value = "low")
    val low: kotlin.Long? = null,

    /* Alias of `medium_count` (#1446). */
    @SerialName(value = "medium")
    val medium: kotlin.Long? = null,

    /* Alias of `total_cves` (#1446). */
    @SerialName(value = "total")
    val total: kotlin.Long? = null

) {


}

