/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Database connection pool statistics.
 *
 * @param activeConnections 
 * @param idleConnections 
 * @param maxConnections 
 * @param propertySize 
 */
@Serializable

data class DbPoolStats (

    @SerialName(value = "active_connections")
    val activeConnections: kotlin.Int,

    @SerialName(value = "idle_connections")
    val idleConnections: kotlin.Int,

    @SerialName(value = "max_connections")
    val maxConnections: kotlin.Int,

    @SerialName(value = "size")
    val propertySize: kotlin.Int

) {


}

