/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attempts 
 * @param createdAt 
 * @param event 
 * @param id 
 * @param payload 
 * @param success 
 * @param webhookId 
 * @param deliveredAt 
 * @param responseBody 
 * @param responseStatus 
 */
@Serializable

data class DeliveryResponse (

    @SerialName(value = "attempts")
    val attempts: kotlin.Int,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "event")
    val event: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "payload")
    val payload: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @Contextual @SerialName(value = "webhook_id")
    val webhookId: java.util.UUID,

    @Contextual @SerialName(value = "delivered_at")
    val deliveredAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "response_body")
    val responseBody: kotlin.String? = null,

    @SerialName(value = "response_status")
    val responseStatus: kotlin.Int? = null

) {


}

