/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A Docker/OCI tag grouped by (image, tag).  `total_size_bytes` is the server-side aggregation of the manifest body plus every referenced layer blob.  This is what the UI should display as the on-disk image size; the previous client-side aggregation that only summed the manifest body itself reported a few kilobytes for images that are hundreds of megabytes on disk (artifact-keeper#1193).  For multi-arch image indexes the size is the sum across all per-arch child manifests recorded in `oci_manifest_refs`, so an `amd64+arm64` index reports the combined storage cost.
 *
 * @param id Representative manifest artifact ID.
 * @param image Image name (no registry host, no tag).  Maps to the OCI v2 `<name>` path segment, which may include slashes (e.g. `library/postgres`).
 * @param isIndex Whether this manifest is a multi-arch image index.
 * @param lastPushedAt Last push (or update) timestamp from the underlying `oci_tags` row.
 * @param layerCount Number of layer blobs referenced by the manifest.  For image indexes this is the sum of layer counts across child manifests.  `0` when the manifest could not be parsed.
 * @param manifestDigest Manifest content digest (e.g. `sha256:abcdef...`).
 * @param repositoryKey Repository key this tag belongs to.
 * @param tag Tag string (e.g. `16-alpine`).  Never a `sha256:...` digest; digest-only references are filtered out of the grouping.
 * @param totalSizeBytes Total size in bytes of the manifest plus all referenced layer blobs. For image indexes, this sums across child manifests.
 * @param scanStatus Rolled-up scan status across all scanners configured for this artifact. `None` when the artifact has never been scanned.  Values surface the aggregate state, not a single scanner's row (see #1497). One of:  * `pending` / `running` -- at least one scanner is still in flight * `completed` -- every per-scan-type latest row is `completed` * `failed` -- every per-scan-type latest row is `failed` * `partial` -- mixed: at least one `completed` AND at least one   `failed`. A green generic scanner (e.g. grype) no longer hides   a failed format-native scanner (e.g. incus) behind a   `completed` label.
 */
@Serializable

data class DockerTagResponse (

    /* Representative manifest artifact ID. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Image name (no registry host, no tag).  Maps to the OCI v2 `<name>` path segment, which may include slashes (e.g. `library/postgres`). */
    @SerialName(value = "image")
    val image: kotlin.String,

    /* Whether this manifest is a multi-arch image index. */
    @SerialName(value = "is_index")
    val isIndex: kotlin.Boolean,

    /* Last push (or update) timestamp from the underlying `oci_tags` row. */
    @Contextual @SerialName(value = "last_pushed_at")
    val lastPushedAt: java.time.OffsetDateTime,

    /* Number of layer blobs referenced by the manifest.  For image indexes this is the sum of layer counts across child manifests.  `0` when the manifest could not be parsed. */
    @SerialName(value = "layer_count")
    val layerCount: kotlin.Int,

    /* Manifest content digest (e.g. `sha256:abcdef...`). */
    @SerialName(value = "manifest_digest")
    val manifestDigest: kotlin.String,

    /* Repository key this tag belongs to. */
    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    /* Tag string (e.g. `16-alpine`).  Never a `sha256:...` digest; digest-only references are filtered out of the grouping. */
    @SerialName(value = "tag")
    val tag: kotlin.String,

    /* Total size in bytes of the manifest plus all referenced layer blobs. For image indexes, this sums across child manifests. */
    @SerialName(value = "total_size_bytes")
    val totalSizeBytes: kotlin.Long,

    /* Rolled-up scan status across all scanners configured for this artifact. `None` when the artifact has never been scanned.  Values surface the aggregate state, not a single scanner's row (see #1497). One of:  * `pending` / `running` -- at least one scanner is still in flight * `completed` -- every per-scan-type latest row is `completed` * `failed` -- every per-scan-type latest row is `failed` * `partial` -- mixed: at least one `completed` AND at least one   `failed`. A green generic scanner (e.g. grype) no longer hides   a failed format-native scanner (e.g. incus) behind a   `completed` label. */
    @SerialName(value = "scan_status")
    val scanStatus: kotlin.String? = null

) {


}

