/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response from analysis update
 *
 * @param analysisState 
 * @param isSuppressed 
 * @param analysisDetails 
 * @param analysisJustification 
 */
@Serializable

data class DtAnalysisResponse (

    @SerialName(value = "analysisState")
    val analysisState: kotlin.String,

    @SerialName(value = "isSuppressed")
    val isSuppressed: kotlin.Boolean,

    @SerialName(value = "analysisDetails")
    val analysisDetails: kotlin.String? = null,

    @SerialName(value = "analysisJustification")
    val analysisJustification: kotlin.String? = null

) {


}

