/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Analysis state for a finding
 *
 * @param isSuppressed 
 * @param details 
 * @param justification 
 * @param response 
 * @param state 
 */
@Serializable

data class DtAnalysis (

    @SerialName(value = "isSuppressed")
    val isSuppressed: kotlin.Boolean,

    @SerialName(value = "details")
    val details: kotlin.String? = null,

    @SerialName(value = "justification")
    val justification: kotlin.String? = null,

    @SerialName(value = "response")
    val response: kotlin.String? = null,

    @SerialName(value = "state")
    val state: kotlin.String? = null

) {


}

