/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.DtLicense

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Full component representation from Dependency-Track
 *
 * @param name 
 * @param uuid 
 * @param cpe 
 * @param group 
 * @param isInternal 
 * @param purl 
 * @param resolvedLicense 
 * @param version 
 */
@Serializable

data class DtComponentFull (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "cpe")
    val cpe: kotlin.String? = null,

    @SerialName(value = "group")
    val group: kotlin.String? = null,

    @SerialName(value = "isInternal")
    val isInternal: kotlin.Boolean? = null,

    @SerialName(value = "purl")
    val purl: kotlin.String? = null,

    @SerialName(value = "resolvedLicense")
    val resolvedLicense: DtLicense? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

