/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Component affected by a vulnerability
 *
 * @param name 
 * @param uuid 
 * @param group 
 * @param purl 
 * @param version 
 */
@Serializable

data class DtComponent (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "group")
    val group: kotlin.String? = null,

    @SerialName(value = "purl")
    val purl: kotlin.String? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

