/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.DtAnalysis
import com.artifactkeeper.client.models.DtAttribution
import com.artifactkeeper.client.models.DtComponent
import com.artifactkeeper.client.models.DtVulnerability

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Vulnerability finding from Dependency-Track
 *
 * @param component 
 * @param vulnerability 
 * @param analysis 
 * @param attribution 
 */
@Serializable

data class DtFinding (

    @SerialName(value = "component")
    val component: DtComponent,

    @SerialName(value = "vulnerability")
    val vulnerability: DtVulnerability,

    @SerialName(value = "analysis")
    val analysis: DtAnalysis? = null,

    @SerialName(value = "attribution")
    val attribution: DtAttribution? = null

) {


}

