/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * License information from Dependency-Track
 *
 * @param name 
 * @param licenseId 
 * @param uuid 
 */
@Serializable

data class DtLicense (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "licenseId")
    val licenseId: kotlin.String? = null,

    @SerialName(value = "uuid")
    val uuid: kotlin.String? = null

) {


}

