/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.DtPolicy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Policy condition that was violated
 *
 * @param `operator` 
 * @param policy 
 * @param subject 
 * @param uuid 
 * @param `value` 
 */
@Serializable

data class DtPolicyCondition (

    @SerialName(value = "operator")
    val `operator`: kotlin.String,

    @SerialName(value = "policy")
    val policy: DtPolicy,

    @SerialName(value = "subject")
    val subject: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

