/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.DtPolicyConditionFull
import com.artifactkeeper.client.models.DtProject

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Full policy representation with conditions and projects
 *
 * @param name 
 * @param policyConditions 
 * @param projects 
 * @param tags 
 * @param uuid 
 * @param violationState 
 * @param includeChildren 
 */
@Serializable

data class DtPolicyFull (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "policyConditions")
    val policyConditions: kotlin.collections.List<DtPolicyConditionFull>,

    @SerialName(value = "projects")
    val projects: kotlin.collections.List<DtProject>,

    @SerialName(value = "tags")
    val tags: kotlin.collections.List<@Contextual kotlinx.serialization.json.JsonElement>,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "violationState")
    val violationState: kotlin.String,

    @SerialName(value = "includeChildren")
    val includeChildren: kotlin.Boolean? = null

) {


}

