/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Full policy condition with all fields
 *
 * @param `operator` 
 * @param subject 
 * @param uuid 
 * @param `value` 
 */
@Serializable

data class DtPolicyConditionFull (

    @SerialName(value = "operator")
    val `operator`: kotlin.String,

    @SerialName(value = "subject")
    val subject: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

