/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Project-level metrics from Dependency-Track
 *
 * @param critical 
 * @param findingsAudited 
 * @param findingsTotal 
 * @param findingsUnaudited 
 * @param firstOccurrence 
 * @param high 
 * @param inheritedRiskScore 
 * @param lastOccurrence 
 * @param low 
 * @param medium 
 * @param policyViolationsFail 
 * @param policyViolationsInfo 
 * @param policyViolationsTotal 
 * @param policyViolationsWarn 
 * @param suppressions 
 * @param unassigned 
 * @param vulnerabilities 
 */
@Serializable

data class DtProjectMetrics (

    @SerialName(value = "critical")
    val critical: kotlin.Long? = null,

    @SerialName(value = "findingsAudited")
    val findingsAudited: kotlin.Long? = null,

    @SerialName(value = "findingsTotal")
    val findingsTotal: kotlin.Long? = null,

    @SerialName(value = "findingsUnaudited")
    val findingsUnaudited: kotlin.Long? = null,

    @SerialName(value = "firstOccurrence")
    val firstOccurrence: kotlin.Long? = null,

    @SerialName(value = "high")
    val high: kotlin.Long? = null,

    @SerialName(value = "inheritedRiskScore")
    val inheritedRiskScore: kotlin.Double? = null,

    @SerialName(value = "lastOccurrence")
    val lastOccurrence: kotlin.Long? = null,

    @SerialName(value = "low")
    val low: kotlin.Long? = null,

    @SerialName(value = "medium")
    val medium: kotlin.Long? = null,

    @SerialName(value = "policyViolationsFail")
    val policyViolationsFail: kotlin.Long? = null,

    @SerialName(value = "policyViolationsInfo")
    val policyViolationsInfo: kotlin.Long? = null,

    @SerialName(value = "policyViolationsTotal")
    val policyViolationsTotal: kotlin.Long? = null,

    @SerialName(value = "policyViolationsWarn")
    val policyViolationsWarn: kotlin.Long? = null,

    @SerialName(value = "suppressions")
    val suppressions: kotlin.Long? = null,

    @SerialName(value = "unassigned")
    val unassigned: kotlin.Long? = null,

    @SerialName(value = "vulnerabilities")
    val vulnerabilities: kotlin.Long? = null

) {


}

