/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Dependency-Track project representation
 *
 * @param name 
 * @param uuid 
 * @param description 
 * @param lastBomImport 
 * @param lastBomImportFormat 
 * @param version 
 */
@Serializable

data class DtProject (

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "uuid")
    val uuid: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "lastBomImport")
    val lastBomImport: kotlin.Long? = null,

    @SerialName(value = "lastBomImportFormat")
    val lastBomImportFormat: kotlin.String? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

