/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param healthy 
 * @param url 
 */
@Serializable

data class DtStatusResponse (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "healthy")
    val healthy: kotlin.Boolean,

    @SerialName(value = "url")
    val url: kotlin.String? = null

) {


}

