/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param enabled 
 * @param eventTypes 
 * @param id 
 * @param recipients 
 * @param updatedAt 
 * @param repositoryId 
 */
@Serializable

data class EmailSubscriptionResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "event_types")
    val eventTypes: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "recipients")
    val recipients: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

