/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Standard error response body returned by all endpoints on failure.
 *
 * @param code Machine-readable error code (e.g. \"NOT_FOUND\", \"VALIDATION_ERROR\")
 * @param message Human-readable error message
 */
@Serializable

data class ErrorResponse (

    /* Machine-readable error code (e.g. \"NOT_FOUND\", \"VALIDATION_ERROR\") */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* Human-readable error message */
    @SerialName(value = "message")
    val message: kotlin.String

) {


}

