/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param created 
 * @param policiesEvaluated 
 * @param removed 
 * @param retroactiveTasksQueued 
 * @param updated 
 */
@Serializable

data class EvaluationResultResponse (

    @SerialName(value = "created")
    val created: kotlin.Int,

    @SerialName(value = "policies_evaluated")
    val policiesEvaluated: kotlin.Int,

    @SerialName(value = "removed")
    val removed: kotlin.Int,

    @SerialName(value = "retroactive_tasks_queued")
    val retroactiveTasksQueued: kotlin.Int,

    @SerialName(value = "updated")
    val updated: kotlin.Int

) {


}

