/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param tokenType 
 */
@Serializable

data class ExchangeCodeResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @SerialName(value = "token_type")
    val tokenType: kotlin.String

) {


}

