/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.FacetValue

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param contentTypes 
 * @param formats 
 * @param repositories 
 */
@Serializable

data class FacetsResponse (

    @SerialName(value = "content_types")
    val contentTypes: kotlin.collections.List<FacetValue>,

    @SerialName(value = "formats")
    val formats: kotlin.collections.List<FacetValue>,

    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<FacetValue>

) {


}

