/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param createdAt 
 * @param id 
 * @param isAcknowledged 
 * @param scanResultId 
 * @param severity 
 * @param title 
 * @param acknowledgedAt 
 * @param acknowledgedBy 
 * @param acknowledgedReason 
 * @param affectedComponent 
 * @param affectedVersion 
 * @param cveId 
 * @param description 
 * @param fixedVersion 
 * @param source 
 * @param sourceUrl 
 */
@Serializable

data class FindingResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_acknowledged")
    val isAcknowledged: kotlin.Boolean,

    @Contextual @SerialName(value = "scan_result_id")
    val scanResultId: java.util.UUID,

    @SerialName(value = "severity")
    val severity: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @Contextual @SerialName(value = "acknowledged_at")
    val acknowledgedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "acknowledged_by")
    val acknowledgedBy: java.util.UUID? = null,

    @SerialName(value = "acknowledged_reason")
    val acknowledgedReason: kotlin.String? = null,

    @SerialName(value = "affected_component")
    val affectedComponent: kotlin.String? = null,

    @SerialName(value = "affected_version")
    val affectedVersion: kotlin.String? = null,

    @SerialName(value = "cve_id")
    val cveId: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "fixed_version")
    val fixedVersion: kotlin.String? = null,

    @SerialName(value = "source")
    val source: kotlin.String? = null,

    @SerialName(value = "source_url")
    val sourceUrl: kotlin.String? = null

) {


}

