/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.FormatHandlerType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Format handler response with additional computed fields.
 *
 * @param createdAt 
 * @param displayName 
 * @param extensions 
 * @param formatKey 
 * @param handlerType 
 * @param id 
 * @param isEnabled 
 * @param priority 
 * @param updatedAt 
 * @param capabilities Plugin capabilities if this is a WASM handler
 * @param description 
 * @param pluginId 
 * @param repositoryCount Number of repositories using this format (computed)
 */
@Serializable

data class FormatHandlerResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @SerialName(value = "extensions")
    val extensions: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "format_key")
    val formatKey: kotlin.String,

    @Contextual @SerialName(value = "handler_type")
    val handlerType: FormatHandlerType,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Plugin capabilities if this is a WASM handler */
    @Contextual @SerialName(value = "capabilities")
    val capabilities: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "plugin_id")
    val pluginId: java.util.UUID? = null,

    /* Number of repositories using this format (computed) */
    @SerialName(value = "repository_count")
    val repositoryCount: kotlin.Long? = null

) {


}

