/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `actual` 
 * @param expected 
 * @param message 
 * @param rule 
 */
@Serializable

data class GateViolationResponse (

    @SerialName(value = "actual")
    val `actual`: kotlin.String,

    @SerialName(value = "expected")
    val expected: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "rule")
    val rule: kotlin.String

) {


}

