/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.GateViolationResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param componentScores 
 * @param gateName 
 * @param healthGrade 
 * @param healthScore 
 * @param passed 
 * @param violations 
 */
@Serializable

data class GateEvaluationResponse (

    @SerialName(value = "action")
    val action: kotlin.String,

    @Contextual @SerialName(value = "component_scores")
    val componentScores: kotlin.Any,

    @SerialName(value = "gate_name")
    val gateName: kotlin.String,

    @SerialName(value = "health_grade")
    val healthGrade: kotlin.String,

    @SerialName(value = "health_score")
    val healthScore: kotlin.Int,

    @SerialName(value = "passed")
    val passed: kotlin.Boolean,

    @SerialName(value = "violations")
    val violations: kotlin.collections.List<GateViolationResponse>

) {


}

