/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param joinedAt 
 * @param userId 
 * @param username 
 * @param displayName 
 */
@Serializable

data class GroupMemberResponse (

    @Contextual @SerialName(value = "joined_at")
    val joinedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "user_id")
    val userId: java.util.UUID,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

