/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.GroupResponse
import com.artifactkeeper.client.models.Pagination

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param pagination 
 */
@Serializable

data class GroupListResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<GroupResponse>,

    @SerialName(value = "pagination")
    val pagination: Pagination

) {


}

