/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.GroupMemberResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param memberCount 
 * @param name 
 * @param updatedAt 
 * @param members Paginated list of group members.
 * @param membersTotal Total number of members in the group. Clients can compare this against the length of `members` to determine whether additional pages exist.
 * @param description 
 */
@Serializable

data class GroupDetailResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "member_count")
    val memberCount: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Paginated list of group members. */
    @SerialName(value = "members")
    val members: kotlin.collections.List<GroupMemberResponse>,

    /* Total number of members in the group. Clients can compare this against the length of `members` to determine whether additional pages exist. */
    @SerialName(value = "members_total")
    val membersTotal: kotlin.Long,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

