/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Growth summary for a time range.
 *
 * @param artifactsAdded 
 * @param artifactsEnd 
 * @param artifactsStart 
 * @param downloadsInPeriod 
 * @param periodEnd 
 * @param periodStart 
 * @param storageBytesEnd 
 * @param storageBytesStart 
 * @param storageGrowthBytes 
 * @param storageGrowthPercent 
 */
@Serializable

data class GrowthSummary (

    @SerialName(value = "artifacts_added")
    val artifactsAdded: kotlin.Long,

    @SerialName(value = "artifacts_end")
    val artifactsEnd: kotlin.Long,

    @SerialName(value = "artifacts_start")
    val artifactsStart: kotlin.Long,

    @SerialName(value = "downloads_in_period")
    val downloadsInPeriod: kotlin.Long,

    @Contextual @SerialName(value = "period_end")
    val periodEnd: java.time.LocalDate,

    @Contextual @SerialName(value = "period_start")
    val periodStart: java.time.LocalDate,

    @SerialName(value = "storage_bytes_end")
    val storageBytesEnd: kotlin.Long,

    @SerialName(value = "storage_bytes_start")
    val storageBytesStart: kotlin.Long,

    @SerialName(value = "storage_growth_bytes")
    val storageGrowthBytes: kotlin.Long,

    @SerialName(value = "storage_growth_percent")
    val storageGrowthPercent: kotlin.Double

) {


}

