/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.RepoHealthResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param avgHealthScore 
 * @param reposGradeA 
 * @param reposGradeB 
 * @param reposGradeC 
 * @param reposGradeD 
 * @param reposGradeF 
 * @param repositories 
 * @param totalArtifactsEvaluated 
 * @param totalRepositories 
 */
@Serializable

data class HealthDashboardResponse (

    @SerialName(value = "avg_health_score")
    val avgHealthScore: kotlin.Int,

    @SerialName(value = "repos_grade_a")
    val reposGradeA: kotlin.Long,

    @SerialName(value = "repos_grade_b")
    val reposGradeB: kotlin.Long,

    @SerialName(value = "repos_grade_c")
    val reposGradeC: kotlin.Long,

    @SerialName(value = "repos_grade_d")
    val reposGradeD: kotlin.Long,

    @SerialName(value = "repos_grade_f")
    val reposGradeF: kotlin.Long,

    @SerialName(value = "repositories")
    val repositories: kotlin.collections.List<RepoHealthResponse>,

    @SerialName(value = "total_artifacts_evaluated")
    val totalArtifactsEvaluated: kotlin.Long,

    @SerialName(value = "total_repositories")
    val totalRepositories: kotlin.Long

) {


}

