/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.DbPoolStats
import com.artifactkeeper.client.models.HealthChecks

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checks 
 * @param demoMode 
 * @param status 
 * @param version 
 * @param commit 
 * @param dbPool 
 * @param dirty 
 */
@Serializable

data class HealthResponse (

    @SerialName(value = "checks")
    val checks: HealthChecks,

    @SerialName(value = "demo_mode")
    val demoMode: kotlin.Boolean,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "commit")
    val commit: kotlin.String? = null,

    @SerialName(value = "db_pool")
    val dbPool: DbPoolStats? = null,

    @SerialName(value = "dirty")
    val dirty: kotlin.Boolean? = null

) {


}

