/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.CheckStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param database 
 * @param storage 
 * @param meilisearch 
 * @param securityScanner 
 */
@Serializable

data class HealthChecks (

    @SerialName(value = "database")
    val database: CheckStatus,

    @SerialName(value = "storage")
    val storage: CheckStatus,

    @SerialName(value = "meilisearch")
    val meilisearch: CheckStatus? = null,

    @SerialName(value = "security_scanner")
    val securityScanner: CheckStatus? = null

) {


}

