/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request for installing from local file path
 *
 * @param path Local filesystem path to plugin directory
 */
@Serializable

data class InstallFromLocalRequest (

    /* Local filesystem path to plugin directory */
    @SerialName(value = "path")
    val path: kotlin.String

) {


}

