/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request to install a plugin from Git
 *
 * @param url Git repository URL
 * @param ref Git ref (tag, branch, or commit)
 */
@Serializable

data class InstallFromGitRequest (

    /* Git repository URL */
    @SerialName(value = "url")
    val url: kotlin.String,

    /* Git ref (tag, branch, or commit) */
    @SerialName(value = "ref")
    val ref: kotlin.String? = null

) {


}

