/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param path Artifact path to evict from the proxy cache. Same shape as the path segment of `GET /api/v1/repositories/{key}/artifacts/{path}`. Path-traversal segments such as `..` are rejected by `ProxyService::cache_storage_key` (covered by `test_invalidate_cache_by_key_rejects_invalid_path`).
 */
@Serializable

data class InvalidateCacheQuery (

    /* Artifact path to evict from the proxy cache. Same shape as the path segment of `GET /api/v1/repositories/{key}/artifacts/{path}`. Path-traversal segments such as `..` are rejected by `ProxyService::cache_storage_key` (covered by `test_invalidate_cache_by_key_rejects_invalid_path`). */
    @SerialName(value = "path")
    val path: kotlin.String

) {


}

