/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param category 
 * @param checkResultId 
 * @param createdAt 
 * @param id 
 * @param isSuppressed 
 * @param severity 
 * @param title 
 * @param description 
 * @param location 
 * @param suppressedAt 
 * @param suppressedBy 
 * @param suppressedReason 
 */
@Serializable

data class IssueResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "category")
    val category: kotlin.String,

    @Contextual @SerialName(value = "check_result_id")
    val checkResultId: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_suppressed")
    val isSuppressed: kotlin.Boolean,

    @SerialName(value = "severity")
    val severity: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "location")
    val location: kotlin.String? = null,

    @Contextual @SerialName(value = "suppressed_at")
    val suppressedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "suppressed_by")
    val suppressedBy: java.util.UUID? = null,

    @SerialName(value = "suppressed_reason")
    val suppressedReason: kotlin.String? = null

) {


}

