/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.SigningKeyPublic

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param propertyKeys 
 * @param total 
 */
@Serializable

data class KeyListResponse (

    @SerialName(value = "keys")
    val propertyKeys: kotlin.collections.List<SigningKeyPublic>,

    @SerialName(value = "total")
    val total: kotlin.Int

) {


}

