/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param message 
 * @param responseTimeMs 
 * @param success 
 */
@Serializable

data class LdapTestResult (

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "response_time_ms")
    val responseTimeMs: kotlin.Long,

    @SerialName(value = "success")
    val success: kotlin.Boolean

) {


}

