/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param displayNameAttribute 
 * @param emailAttribute 
 * @param groupsAttribute 
 * @param hasBindPassword 
 * @param id 
 * @param isEnabled 
 * @param name 
 * @param priority 
 * @param serverUrl 
 * @param updatedAt 
 * @param useStarttls 
 * @param userBaseDn 
 * @param userFilter 
 * @param usernameAttribute 
 * @param adminGroupDn 
 * @param bindDn 
 * @param groupBaseDn 
 * @param groupFilter 
 */
@Serializable

data class LdapConfigResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "display_name_attribute")
    val displayNameAttribute: kotlin.String,

    @SerialName(value = "email_attribute")
    val emailAttribute: kotlin.String,

    @SerialName(value = "groups_attribute")
    val groupsAttribute: kotlin.String,

    @SerialName(value = "has_bind_password")
    val hasBindPassword: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @SerialName(value = "server_url")
    val serverUrl: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "use_starttls")
    val useStarttls: kotlin.Boolean,

    @SerialName(value = "user_base_dn")
    val userBaseDn: kotlin.String,

    @SerialName(value = "user_filter")
    val userFilter: kotlin.String,

    @SerialName(value = "username_attribute")
    val usernameAttribute: kotlin.String,

    @SerialName(value = "admin_group_dn")
    val adminGroupDn: kotlin.String? = null,

    @SerialName(value = "bind_dn")
    val bindDn: kotlin.String? = null,

    @SerialName(value = "group_base_dn")
    val groupBaseDn: kotlin.String? = null,

    @SerialName(value = "group_filter")
    val groupFilter: kotlin.String? = null

) {


}

