/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Result of license compliance check.
 *
 * @param compliant 
 * @param violations 
 * @param warnings 
 */
@Serializable

data class LicenseCheckResult (

    @SerialName(value = "compliant")
    val compliant: kotlin.Boolean,

    @SerialName(value = "violations")
    val violations: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {


}

