/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param isActive 
 * @param isAdmin 
 * @param page 
 * @param perPage 
 * @param search 
 */
@Serializable

data class ListUsersQuery (

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean? = null,

    @SerialName(value = "is_admin")
    val isAdmin: kotlin.Boolean? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "search")
    val search: kotlin.String? = null

) {


}

