/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param pathPrefix 
 * @param perPage 
 * @param q 
 */
@Serializable

data class ListArtifactsQuery (

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "path_prefix")
    val pathPrefix: kotlin.String? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "q")
    val q: kotlin.String? = null

) {


}

