/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param format 
 * @param page 
 * @param perPage 
 * @param q 
 * @param type 
 */
@Serializable

data class ListRepositoriesQuery (

    @SerialName(value = "format")
    val format: kotlin.String? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "q")
    val q: kotlin.String? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null

) {


}

