/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param groupBy Server-side artifact grouping.  Supported values: - `maven_component`: Maven/Gradle artifacts are grouped by   groupId, artifactId, and version.  Individual files (jar, pom,   checksums) appear in the `artifact_files` array of each component. - `docker_tag`: Docker/OCI artifacts are grouped by (image, tag),   with `total_size_bytes` summed across the manifest config and   referenced layer blobs.  The grouped rows are returned in the   `docker_tags` array.
 * @param page 
 * @param pathPrefix 
 * @param perPage 
 * @param q 
 */
@Serializable

data class ListArtifactsQuery (

    /* Server-side artifact grouping.  Supported values: - `maven_component`: Maven/Gradle artifacts are grouped by   groupId, artifactId, and version.  Individual files (jar, pom,   checksums) appear in the `artifact_files` array of each component. - `docker_tag`: Docker/OCI artifacts are grouped by (image, tag),   with `total_size_bytes` summed across the manifest config and   referenced layer blobs.  The grouped rows are returned in the   `docker_tags` array. */
    @SerialName(value = "group_by")
    val groupBy: kotlin.String? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "path_prefix")
    val pathPrefix: kotlin.String? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "q")
    val q: kotlin.String? = null

) {


}

