/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param accessToken 
 * @param expiresIn 
 * @param mustChangePassword 
 * @param refreshToken 
 * @param tokenType 
 * @param totpRequired 
 * @param totpToken 
 */
@Serializable

data class LoginResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @SerialName(value = "expires_in")
    val expiresIn: kotlin.Long,

    @SerialName(value = "must_change_password")
    val mustChangePassword: kotlin.Boolean,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @SerialName(value = "token_type")
    val tokenType: kotlin.String,

    @SerialName(value = "totp_required")
    val totpRequired: kotlin.Boolean? = null,

    @SerialName(value = "totp_token")
    val totpToken: kotlin.String? = null

) {


}

