/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A Maven component grouped by GAV (groupId, artifactId, version).  Each component collects the individual files (jar, pom, checksums, etc.) that share the same Maven coordinates.
 *
 * @param artifactFiles Individual filenames belonging to this component.
 * @param artifactId Maven artifactId (e.g. `junit-jupiter-api`).
 * @param createdAt Earliest creation timestamp among the component files.
 * @param downloadCount Total download count across all files in this component.
 * @param format Repository format (always `maven` or `gradle`).
 * @param groupId Maven groupId with dots (e.g. `org.junit.jupiter`).
 * @param id Representative artifact ID (the first file in the group).
 * @param repositoryKey Repository key this component belongs to.
 * @param sizeBytes Total size in bytes across all files in this component.
 * @param version Maven version string (e.g. `5.11.0`).
 */
@Serializable

data class MavenComponentResponse (

    /* Individual filenames belonging to this component. */
    @SerialName(value = "artifact_files")
    val artifactFiles: kotlin.collections.List<kotlin.String>,

    /* Maven artifactId (e.g. `junit-jupiter-api`). */
    @SerialName(value = "artifact_id")
    val artifactId: kotlin.String,

    /* Earliest creation timestamp among the component files. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Total download count across all files in this component. */
    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    /* Repository format (always `maven` or `gradle`). */
    @SerialName(value = "format")
    val format: kotlin.String,

    /* Maven groupId with dots (e.g. `org.junit.jupiter`). */
    @SerialName(value = "group_id")
    val groupId: kotlin.String,

    /* Representative artifact ID (the first file in the group). */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Repository key this component belongs to. */
    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    /* Total size in bytes across all files in this component. */
    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    /* Maven version string (e.g. `5.11.0`). */
    @SerialName(value = "version")
    val version: kotlin.String

) {


}

