/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param completedItems 
 * @param config 
 * @param createdAt 
 * @param failedItems 
 * @param id 
 * @param jobType 
 * @param skippedItems 
 * @param sourceConnectionId 
 * @param status 
 * @param totalBytes 
 * @param totalItems 
 * @param transferredBytes 
 * @param createdBy 
 * @param errorSummary 
 * @param finishedAt 
 * @param startedAt 
 */
@Serializable

data class MigrationJobRow (

    @SerialName(value = "completed_items")
    val completedItems: kotlin.Int,

    @Contextual @SerialName(value = "config")
    val config: kotlinx.serialization.json.JsonElement,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "failed_items")
    val failedItems: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "job_type")
    val jobType: kotlin.String,

    @SerialName(value = "skipped_items")
    val skippedItems: kotlin.Int,

    @Contextual @SerialName(value = "source_connection_id")
    val sourceConnectionId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "total_bytes")
    val totalBytes: kotlin.Long,

    @SerialName(value = "total_items")
    val totalItems: kotlin.Int,

    @SerialName(value = "transferred_bytes")
    val transferredBytes: kotlin.Long,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID? = null,

    @SerialName(value = "error_summary")
    val errorSummary: kotlin.String? = null,

    @Contextual @SerialName(value = "finished_at")
    val finishedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null

) {


}

