/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param itemType 
 * @param jobId 
 * @param retryCount 
 * @param sizeBytes 
 * @param sourcePath 
 * @param status 
 * @param checksumSource 
 * @param checksumTarget 
 * @param completedAt 
 * @param errorMessage 
 * @param startedAt 
 * @param targetPath 
 */
@Serializable

data class MigrationItemResponse (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "item_type")
    val itemType: kotlin.String,

    @Contextual @SerialName(value = "job_id")
    val jobId: java.util.UUID,

    @SerialName(value = "retry_count")
    val retryCount: kotlin.Int,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "source_path")
    val sourcePath: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "checksum_source")
    val checksumSource: kotlin.String? = null,

    @SerialName(value = "checksum_target")
    val checksumTarget: kotlin.String? = null,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "target_path")
    val targetPath: kotlin.String? = null

) {


}

