/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param errors 
 * @param generatedAt 
 * @param id 
 * @param jobId 
 * @param recommendations 
 * @param summary 
 * @param warnings 
 */
@Serializable

data class MigrationReportResponse (

    @Contextual @SerialName(value = "errors")
    val errors: kotlin.Any,

    @Contextual @SerialName(value = "generated_at")
    val generatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "job_id")
    val jobId: java.util.UUID,

    @Contextual @SerialName(value = "recommendations")
    val recommendations: kotlin.Any,

    @Contextual @SerialName(value = "summary")
    val summary: kotlin.Any,

    @Contextual @SerialName(value = "warnings")
    val warnings: kotlin.Any

) {


}

