/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param errors 
 * @param generatedAt 
 * @param id 
 * @param jobId 
 * @param recommendations 
 * @param summary 
 * @param warnings 
 */
@Serializable

data class MigrationReportResponse (

    @Contextual @SerialName(value = "errors")
    val errors: kotlinx.serialization.json.JsonElement,

    @Contextual @SerialName(value = "generated_at")
    val generatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "job_id")
    val jobId: java.util.UUID,

    @Contextual @SerialName(value = "recommendations")
    val recommendations: kotlinx.serialization.json.JsonElement,

    @Contextual @SerialName(value = "summary")
    val summary: kotlinx.serialization.json.JsonElement,

    @Contextual @SerialName(value = "warnings")
    val warnings: kotlinx.serialization.json.JsonElement

) {


}

