/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param concurrentTransfersLimit 
 * @param maxBandwidthBps 
 * @param syncWindowEnd 
 * @param syncWindowStart 
 * @param syncWindowTimezone 
 */
@Serializable

data class NetworkProfileBody (

    @SerialName(value = "concurrent_transfers_limit")
    val concurrentTransfersLimit: kotlin.Int? = null,

    @SerialName(value = "max_bandwidth_bps")
    val maxBandwidthBps: kotlin.Long? = null,

    @SerialName(value = "sync_window_end")
    val syncWindowEnd: kotlin.String? = null,

    @SerialName(value = "sync_window_start")
    val syncWindowStart: kotlin.String? = null,

    @SerialName(value = "sync_window_timezone")
    val syncWindowTimezone: kotlin.String? = null

) {


}

