/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.OciBlobRepoFootprint

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Read-only OCI blob storage footprint report (issue #1408).  This is a **reporting-only** view. It performs no deletion and takes no locks. It surfaces how much storage the tracked `oci_blobs` rows account for so operators can see the magnitude of un-reclaimed blob layers before any garbage-collection mechanism is enabled.  It deliberately does NOT attempt to classify which blobs are \"reclaimable orphans\": that requires a manifest -> blob reference table that does not yet exist in the schema, and any per-`(repository_id, digest)` orphan heuristic would mis-handle the cross-repo dedup case (multiple `oci_blobs` rows, one physical object) and report in-use blobs as reclaimable. The numbers here are exact aggregates only.
 *
 * @param agedDistinctDigests Distinct digests older than `grace_hours` (eligible to be *considered* by a future GC sweep once a reference table exists). Reporting only.
 * @param agedPhysicalBytes Physical bytes (distinct-digest) older than `grace_hours`.
 * @param distinctDigests Number of distinct blob digests (content-addressed identities). When this is smaller than `total_blob_rows`, the difference is cross-repo deduplication: rows that share one physical storage object.
 * @param graceHours Grace window (hours) applied to the `aged_*` figures below.
 * @param logicalBytes Sum of `size_bytes` over every `oci_blobs` row. Double-counts deduplicated blobs once per referencing repository.
 * @param perRepository Per-repository logical footprint, largest `logical_bytes` first.
 * @param physicalBytes Sum of `size_bytes` counting each distinct digest exactly once. This approximates the physical bytes occupied in the storage backend.
 * @param totalBlobRows Total number of `oci_blobs` rows across all repositories.
 */
@Serializable

data class OciBlobFootprintReport (

    /* Distinct digests older than `grace_hours` (eligible to be *considered* by a future GC sweep once a reference table exists). Reporting only. */
    @SerialName(value = "aged_distinct_digests")
    val agedDistinctDigests: kotlin.Long,

    /* Physical bytes (distinct-digest) older than `grace_hours`. */
    @SerialName(value = "aged_physical_bytes")
    val agedPhysicalBytes: kotlin.Long,

    /* Number of distinct blob digests (content-addressed identities). When this is smaller than `total_blob_rows`, the difference is cross-repo deduplication: rows that share one physical storage object. */
    @SerialName(value = "distinct_digests")
    val distinctDigests: kotlin.Long,

    /* Grace window (hours) applied to the `aged_*` figures below. */
    @SerialName(value = "grace_hours")
    val graceHours: kotlin.Long,

    /* Sum of `size_bytes` over every `oci_blobs` row. Double-counts deduplicated blobs once per referencing repository. */
    @SerialName(value = "logical_bytes")
    val logicalBytes: kotlin.Long,

    /* Per-repository logical footprint, largest `logical_bytes` first. */
    @SerialName(value = "per_repository")
    val perRepository: kotlin.collections.List<OciBlobRepoFootprint>,

    /* Sum of `size_bytes` counting each distinct digest exactly once. This approximates the physical bytes occupied in the storage backend. */
    @SerialName(value = "physical_bytes")
    val physicalBytes: kotlin.Long,

    /* Total number of `oci_blobs` rows across all repositories. */
    @SerialName(value = "total_blob_rows")
    val totalBlobRows: kotlin.Long

) {


}

