/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Per-repository row in the OCI blob footprint report.
 *
 * @param blobRows Number of `oci_blobs` rows attributed to this repository.
 * @param logicalBytes Sum of `oci_blobs.size_bytes` for this repository's rows. Because OCI blob storage is content-addressed and deduplicated across repos, the same physical bytes can be counted under more than one repository here; see [`OciBlobFootprintReport::physical_bytes`] for the dedup-aware total.
 * @param repositoryId Repository id owning these `oci_blobs` rows.
 */
@Serializable

data class OciBlobRepoFootprint (

    /* Number of `oci_blobs` rows attributed to this repository. */
    @SerialName(value = "blob_rows")
    val blobRows: kotlin.Long,

    /* Sum of `oci_blobs.size_bytes` for this repository's rows. Because OCI blob storage is content-addressed and deduplicated across repos, the same physical bytes can be counted under more than one repository here; see [`OciBlobFootprintReport::physical_bytes`] for the dedup-aware total. */
    @SerialName(value = "logical_bytes")
    val logicalBytes: kotlin.Long,

    /* Repository id owning these `oci_blobs` rows. */
    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID

) {


}

