/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attributeMapping 
 * @param autoCreateUsers 
 * @param clientId 
 * @param createdAt 
 * @param hasSecret 
 * @param id 
 * @param isEnabled 
 * @param issuerUrl 
 * @param mapGroupsToGroups 
 * @param name 
 * @param pkceEnabled 
 * @param scopes 
 * @param updatedAt 
 */
@Serializable

data class OidcConfigResponse (

    @Contextual @SerialName(value = "attribute_mapping")
    val attributeMapping: kotlin.Any,

    @SerialName(value = "auto_create_users")
    val autoCreateUsers: kotlin.Boolean,

    @SerialName(value = "client_id")
    val clientId: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "has_secret")
    val hasSecret: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "issuer_url")
    val issuerUrl: kotlin.String,

    @SerialName(value = "map_groups_to_groups")
    val mapGroupsToGroups: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "pkce_enabled")
    val pkceEnabled: kotlin.Boolean,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

