/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param checksumSha256 
 * @param createdAt 
 * @param downloadCount 
 * @param sizeBytes 
 * @param version 
 */
@Serializable

data class PackageVersionResponse (

    @SerialName(value = "checksum_sha256")
    val checksumSha256: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "version")
    val version: kotlin.String

) {


}

