/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param downloadCount 
 * @param format 
 * @param id 
 * @param metadata 
 * @param name 
 * @param repositoryKey 
 * @param sizeBytes 
 * @param updatedAt 
 * @param version 
 * @param description 
 */
@Serializable

data class PackageRow (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @SerialName(value = "format")
    val format: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "metadata")
    val metadata: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

