/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param stagingRepoId 
 * @param limit 
 * @param offset 
 * @param status 
 */
@Serializable

data class PackageListQuery (

    @Contextual @SerialName(value = "staging_repo_id")
    val stagingRepoId: java.util.UUID,

    @SerialName(value = "limit")
    val limit: kotlin.Long? = null,

    @SerialName(value = "offset")
    val offset: kotlin.Long? = null,

    @SerialName(value = "status")
    val status: kotlin.String? = null

) {


}

