/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Pagination metadata for list responses.  Used consistently across all paginated API endpoints to provide standard pagination information to clients.
 *
 * @param page Current page number (1-indexed)
 * @param perPage Number of items per page
 * @param total Total number of items across all pages
 * @param totalPages Total number of pages
 */
@Serializable

data class Pagination (

    /* Current page number (1-indexed) */
    @SerialName(value = "page")
    val page: kotlin.Int,

    /* Number of items per page */
    @SerialName(value = "per_page")
    val perPage: kotlin.Int,

    /* Total number of items across all pages */
    @SerialName(value = "total")
    val total: kotlin.Long,

    /* Total number of pages */
    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int

) {


}

