/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param page 
 * @param perPage 
 * @param total 
 * @param totalPages 
 */
@Serializable

data class PaginationInfo (

    @SerialName(value = "page")
    val page: kotlin.Int,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int,

    @SerialName(value = "total")
    val total: kotlin.Long,

    @SerialName(value = "total_pages")
    val totalPages: kotlin.Int

) {


}

