/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Supported webhook payload templates.  Controls how the outgoing JSON body is structured when delivering a webhook. The `Generic` variant preserves backward compatibility with the original flat JSON format.
 *
 * Values: generic,slack,microsoft_teams,discord,mattermost
 */
@Serializable
enum class PayloadTemplate(val value: kotlin.String) {

    @SerialName(value = "generic")
    generic("generic"),

    @SerialName(value = "slack")
    slack("slack"),

    @SerialName(value = "microsoft_teams")
    microsoft_teams("microsoft_teams"),

    @SerialName(value = "discord")
    discord("discord"),

    @SerialName(value = "mattermost")
    mattermost("mattermost");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PayloadTemplate) "$data" else null

        /**
         * Returns a valid [PayloadTemplate] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PayloadTemplate? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


