/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param bytesTransferredTotal 
 * @param id 
 * @param sharedArtifactsCount 
 * @param sharedChunksCount 
 * @param status 
 * @param targetPeerId 
 * @param transferFailureCount 
 * @param transferSuccessCount 
 * @param bandwidthEstimateBps 
 * @param lastProbedAt 
 * @param lastTransferAt 
 * @param latencyMs 
 */
@Serializable

data class PeerResponse (

    @SerialName(value = "bytes_transferred_total")
    val bytesTransferredTotal: kotlin.Long,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "shared_artifacts_count")
    val sharedArtifactsCount: kotlin.Int,

    @SerialName(value = "shared_chunks_count")
    val sharedChunksCount: kotlin.Int,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "target_peer_id")
    val targetPeerId: java.util.UUID,

    @SerialName(value = "transfer_failure_count")
    val transferFailureCount: kotlin.Int,

    @SerialName(value = "transfer_success_count")
    val transferSuccessCount: kotlin.Int,

    @SerialName(value = "bandwidth_estimate_bps")
    val bandwidthEstimateBps: kotlin.Long? = null,

    @Contextual @SerialName(value = "last_probed_at")
    val lastProbedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_transfer_at")
    val lastTransferAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "latency_ms")
    val latencyMs: kotlin.Int? = null

) {


}

