/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param key 
 * @param peerInstanceId 
 * @param `value` 
 */
@Serializable

data class PeerLabelResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "key")
    val key: kotlin.String,

    @Contextual @SerialName(value = "peer_instance_id")
    val peerInstanceId: java.util.UUID,

    @SerialName(value = "value")
    val `value`: kotlin.String

) {


}

