/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param all 
 * @param matchLabels 
 * @param matchPeers 
 * @param matchRegion 
 */
@Serializable

data class PeerSelectorSchema (

    @SerialName(value = "all")
    val all: kotlin.Boolean? = null,

    @SerialName(value = "match_labels")
    val matchLabels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "match_peers")
    val matchPeers: kotlin.collections.List<@Contextual java.util.UUID>? = null,

    @SerialName(value = "match_region")
    val matchRegion: kotlin.String? = null

) {


}

