/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Fine-grained permissions enforcement status.
 *
 * @param enforcementEnabled Whether those rules are actively enforced on API requests. The permission-check middleware and handler guards are wired in, so this is `true` when the server is running.
 * @param rulesExist Whether the permissions table (from migration 018) has any rows. When true, an administrator has configured permission rules.
 */
@Serializable

data class PermissionsConfig (

    /* Whether those rules are actively enforced on API requests. The permission-check middleware and handler guards are wired in, so this is `true` when the server is running. */
    @SerialName(value = "enforcement_enabled")
    val enforcementEnabled: kotlin.Boolean,

    /* Whether the permissions table (from migration 018) has any rows. When true, an administrator has configured permission rules. */
    @SerialName(value = "rules_exist")
    val rulesExist: kotlin.Boolean

) {


}

