/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Plugin signature-verification (supply-chain) policy status.  Exposes only booleans — never the trusted key material itself — so frontends and operators can see whether unsigned plugin installs are rejected and whether a trusted publisher key has been provisioned.
 *
 * @param required Whether a valid signature is required to install a WASM plugin.
 * @param trustedKeyConfigured Whether an operator trusted public key has been configured. When `required` is true but this is false, every install is rejected (fail-closed).
 */
@Serializable

data class PluginSigningConfig (

    /* Whether a valid signature is required to install a WASM plugin. */
    @SerialName(value = "required")
    val required: kotlin.Boolean,

    /* Whether an operator trusted public key has been configured. When `required` is true but this is false, every install is rejected (fail-closed). */
    @SerialName(value = "trusted_key_configured")
    val trustedKeyConfigured: kotlin.Boolean

) {


}

