/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param config 
 * @param pluginId 
 * @param schema 
 */
@Serializable

data class PluginConfigResponse (

    @Contextual @SerialName(value = "config")
    val config: kotlin.Any,

    @Contextual @SerialName(value = "plugin_id")
    val pluginId: java.util.UUID,

    @Contextual @SerialName(value = "schema")
    val schema: kotlin.Any

) {


}

