/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Plugin type
 *
 * Values: FORMAT_HANDLER,STORAGE_BACKEND,AUTHENTICATION,AUTHORIZATION,WEBHOOK,CUSTOM
 */
@Serializable
enum class PluginType(val value: kotlin.String) {

    @SerialName(value = "format_handler")
    FORMAT_HANDLER("format_handler"),

    @SerialName(value = "storage_backend")
    STORAGE_BACKEND("storage_backend"),

    @SerialName(value = "authentication")
    AUTHENTICATION("authentication"),

    @SerialName(value = "authorization")
    AUTHORIZATION("authorization"),

    @SerialName(value = "webhook")
    WEBHOOK("webhook"),

    @SerialName(value = "custom")
    CUSTOM("custom");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PluginType) "$data" else null

        /**
         * Returns a valid [PluginType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PluginType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

