/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param configSchema 
 * @param displayName 
 * @param id 
 * @param installedAt 
 * @param name 
 * @param pluginType 
 * @param status 
 * @param version 
 * @param author 
 * @param description 
 * @param enabledAt 
 * @param homepage 
 */
@Serializable

data class PluginResponse (

    @Contextual @SerialName(value = "config_schema")
    val configSchema: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "installed_at")
    val installedAt: java.time.OffsetDateTime,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "plugin_type")
    val pluginType: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "author")
    val author: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "enabled_at")
    val enabledAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null

) {


}

