/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Plugin type
 *
 * Values: format_handler,storage_backend,authentication,authorization,webhook,custom
 */
@Serializable
enum class PluginType(val value: kotlin.String) {

    @SerialName(value = "format_handler")
    format_handler("format_handler"),

    @SerialName(value = "storage_backend")
    storage_backend("storage_backend"),

    @SerialName(value = "authentication")
    authentication("authentication"),

    @SerialName(value = "authorization")
    authorization("authorization"),

    @SerialName(value = "webhook")
    webhook("webhook"),

    @SerialName(value = "custom")
    custom("custom");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PluginType) "$data" else null

        /**
         * Returns a valid [PluginType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PluginType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


