/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockOnFail 
 * @param blockUnscanned 
 * @param createdAt 
 * @param id 
 * @param isEnabled 
 * @param maxSeverity 
 * @param name 
 * @param requireSignature 
 * @param updatedAt 
 * @param maxArtifactAgeDays 
 * @param minStagingHours 
 * @param repositoryId 
 */
@Serializable

data class PolicyResponse (

    @SerialName(value = "block_on_fail")
    val blockOnFail: kotlin.Boolean,

    @SerialName(value = "block_unscanned")
    val blockUnscanned: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "max_severity")
    val maxSeverity: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "require_signature")
    val requireSignature: kotlin.Boolean,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "max_artifact_age_days")
    val maxArtifactAgeDays: kotlin.Int? = null,

    @SerialName(value = "min_staging_hours")
    val minStagingHours: kotlin.Int? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

