/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockOnFail 
 * @param blockUnscanned 
 * @param createdAt 
 * @param id 
 * @param isEnabled 
 * @param maxSeverity 
 * @param name 
 * @param updatedAt 
 * @param repositoryId 
 */
@Serializable

data class PolicyResponse (

    @SerialName(value = "block_on_fail")
    val blockOnFail: kotlin.Boolean,

    @SerialName(value = "block_unscanned")
    val blockUnscanned: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "max_severity")
    val maxSeverity: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

