/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Result of a lifecycle policy dry-run or execution.
 *
 * @param artifactsMatched 
 * @param artifactsRemoved 
 * @param bytesFreed 
 * @param dryRun 
 * @param errors 
 * @param policyId 
 * @param policyName 
 */
@Serializable

data class PolicyExecutionResult (

    @SerialName(value = "artifacts_matched")
    val artifactsMatched: kotlin.Long,

    @SerialName(value = "artifacts_removed")
    val artifactsRemoved: kotlin.Long,

    @SerialName(value = "bytes_freed")
    val bytesFreed: kotlin.Long,

    @SerialName(value = "dry_run")
    val dryRun: kotlin.Boolean,

    @SerialName(value = "errors")
    val errors: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "policy_id")
    val policyId: java.util.UUID,

    @SerialName(value = "policy_name")
    val policyName: kotlin.String

) {


}

