/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body for previewing which repositories a selector matches.
 *
 * @param repoSelector The repository selector to evaluate.
 */
@Serializable

data class PreviewRepoSelectorRequest (

    /* The repository selector to evaluate. */
    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlinx.serialization.json.JsonElement

) {


}

