/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param name 
 * @param artifactFilter 
 * @param description 
 * @param enabled 
 * @param peerSelector 
 * @param precedence 
 * @param priority 
 * @param replicationMode 
 * @param repoSelector 
 */
@Serializable

data class PreviewPolicyPayload (

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "artifact_filter")
    val artifactFilter: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "peer_selector")
    val peerSelector: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "precedence")
    val precedence: kotlin.Int? = null,

    @SerialName(value = "priority")
    val priority: kotlin.Int? = null,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String? = null,

    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlinx.serialization.json.JsonElement? = null

) {


}

