/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.MatchedPeerSchema
import com.artifactkeeper.client.models.MatchedRepoSchema

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param matchedPeers 
 * @param matchedRepositories 
 * @param subscriptionCount 
 */
@Serializable

data class PreviewResultResponse (

    @SerialName(value = "matched_peers")
    val matchedPeers: kotlin.collections.List<MatchedPeerSchema>,

    @SerialName(value = "matched_repositories")
    val matchedRepositories: kotlin.collections.List<MatchedRepoSchema>,

    @SerialName(value = "subscription_count")
    val subscriptionCount: kotlin.Int

) {


}

