/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.MatchedRepoResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response for the repo selector preview endpoint.
 *
 * @param matchedRepositories 
 * @param total 
 */
@Serializable

data class PreviewRepoSelectorResponse (

    @SerialName(value = "matched_repositories")
    val matchedRepositories: kotlin.collections.List<MatchedRepoResponse>,

    @SerialName(value = "total")
    val total: kotlin.Int

) {


}

