/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param latencyMs 
 * @param targetPeerId 
 * @param bandwidthEstimateBps 
 */
@Serializable

data class ProbeBody (

    @SerialName(value = "latency_ms")
    val latencyMs: kotlin.Int,

    @Contextual @SerialName(value = "target_peer_id")
    val targetPeerId: java.util.UUID,

    @SerialName(value = "bandwidth_estimate_bps")
    val bandwidthEstimateBps: kotlin.Long? = null

) {


}

