/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param notes 
 * @param skipPolicyCheck 
 * @param targetRepository Target release repository key. When omitted, the staging repository's linked release target (from `repository_config`) is used instead.
 */
@Serializable

data class PromoteArtifactRequest (

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @SerialName(value = "skip_policy_check")
    val skipPolicyCheck: kotlin.Boolean? = null,

    /* Target release repository key. When omitted, the staging repository's linked release target (from `repository_config`) is used instead. */
    @SerialName(value = "target_repository")
    val targetRepository: kotlin.String? = null

) {


}

