/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param autoPromote 
 * @param createdAt 
 * @param id 
 * @param isEnabled 
 * @param name 
 * @param requireSignature 
 * @param sourceRepoId 
 * @param targetRepoId 
 * @param updatedAt 
 * @param allowedLicenses 
 * @param maxArtifactAgeDays 
 * @param maxCveSeverity 
 * @param minHealthScore 
 * @param minStagingHours 
 */
@Serializable

data class PromotionRuleResponse (

    @SerialName(value = "auto_promote")
    val autoPromote: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "require_signature")
    val requireSignature: kotlin.Boolean,

    @Contextual @SerialName(value = "source_repo_id")
    val sourceRepoId: java.util.UUID,

    @Contextual @SerialName(value = "target_repo_id")
    val targetRepoId: java.util.UUID,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "allowed_licenses")
    val allowedLicenses: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "max_artifact_age_days")
    val maxArtifactAgeDays: kotlin.Int? = null,

    @SerialName(value = "max_cve_severity")
    val maxCveSeverity: kotlin.String? = null,

    @SerialName(value = "min_health_score")
    val minHealthScore: kotlin.Int? = null,

    @SerialName(value = "min_staging_hours")
    val minStagingHours: kotlin.Int? = null

) {


}

