/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param artifactPath 
 * @param createdAt 
 * @param id 
 * @param sourceRepoKey 
 * @param targetRepoKey 
 * @param notes 
 * @param policyResult 
 * @param promotedBy 
 * @param promotedByUsername 
 */
@Serializable

data class PromotionHistoryEntry (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "artifact_path")
    val artifactPath: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "source_repo_key")
    val sourceRepoKey: kotlin.String,

    @SerialName(value = "target_repo_key")
    val targetRepoKey: kotlin.String,

    @SerialName(value = "notes")
    val notes: kotlin.String? = null,

    @Contextual @SerialName(value = "policy_result")
    val policyResult: kotlinx.serialization.json.JsonElement? = null,

    @Contextual @SerialName(value = "promoted_by")
    val promotedBy: java.util.UUID? = null,

    @SerialName(value = "promoted_by_username")
    val promotedByUsername: kotlin.String? = null

) {


}

