/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.PromotionRuleResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param items 
 * @param total 
 */
@Serializable

data class PromotionRuleListResponse (

    @SerialName(value = "items")
    val items: kotlin.collections.List<PromotionRuleResponse>,

    @SerialName(value = "total")
    val total: kotlin.Int

) {


}

