/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param page 
 * @param perPage 
 */
@Serializable

data class PromotionHistoryQuery (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null

) {


}

