/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Body for declaring that a locally-owned PyPI project tracks an upstream one.
 *
 * @param tracksUrl Upstream Simple index project URL this local project tracks, e.g. `https://pypi.org/simple/acme-sdk/`. Recorded and emitted as the PEP 708 `tracks` value.
 */
@Serializable

data class PypiTrackRequest (

    /* Upstream Simple index project URL this local project tracks, e.g. `https://pypi.org/simple/acme-sdk/`. Recorded and emitted as the PEP 708 `tracks` value. */
    @SerialName(value = "tracks_url")
    val tracksUrl: kotlin.String

) {


}

