/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param isBlocked 
 * @param quarantineStatus 
 * @param quarantineUntil 
 */
@Serializable

data class QuarantineStatusResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "is_blocked")
    val isBlocked: kotlin.Boolean,

    @SerialName(value = "quarantine_status")
    val quarantineStatus: kotlin.String? = null,

    @Contextual @SerialName(value = "quarantine_until")
    val quarantineUntil: java.time.OffsetDateTime? = null

) {


}

