/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param apiKey 
 * @param endpointUrl 
 * @param name 
 * @param syncFilter 
 * @param cacheSizeBytes 
 * @param region 
 */
@Serializable

data class RegisterPeerRequest (

    @SerialName(value = "api_key")
    val apiKey: kotlin.String,

    @SerialName(value = "endpoint_url")
    val endpointUrl: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "sync_filter")
    val syncFilter: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "cache_size_bytes")
    val cacheSizeBytes: kotlin.Long? = null,

    @SerialName(value = "region")
    val region: kotlin.String? = null

) {


}

