/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactsIndexed 
 * @param message 
 * @param repositoriesIndexed 
 */
@Serializable

data class ReindexResponse (

    @SerialName(value = "artifacts_indexed")
    val artifactsIndexed: kotlin.Long,

    @SerialName(value = "message")
    val message: kotlin.String,

    @SerialName(value = "repositories_indexed")
    val repositoriesIndexed: kotlin.Long

) {


}

