/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param linked Whether this staging repository has a linked release target.
 * @param releaseRepositoryId The release repository ID, if linked.
 * @param releaseRepositoryKey The release repository key, if linked.
 */
@Serializable

data class ReleaseTargetResponse (

    /* Whether this staging repository has a linked release target. */
    @SerialName(value = "linked")
    val linked: kotlin.Boolean,

    /* The release repository ID, if linked. */
    @Contextual @SerialName(value = "release_repository_id")
    val releaseRepositoryId: java.util.UUID? = null,

    /* The release repository key, if linked. */
    @SerialName(value = "release_repository_key")
    val releaseRepositoryKey: kotlin.String? = null

) {


}

