/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactCount 
 * @param compatibility 
 * @param key 
 * @param packageType 
 * @param totalSizeBytes 
 * @param type 
 * @param warnings 
 */
@Serializable

data class RepositoryAssessment (

    @SerialName(value = "artifact_count")
    val artifactCount: kotlin.Long,

    @SerialName(value = "compatibility")
    val compatibility: kotlin.String,

    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "package_type")
    val packageType: kotlin.String,

    @SerialName(value = "total_size_bytes")
    val totalSizeBytes: kotlin.Long,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>

) {


}

