/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.ScanConfigResponse
import com.artifactkeeper.client.models.ScoreResponse

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param config 
 * @param score 
 */
@Serializable

data class RepoSecurityResponse (

    @SerialName(value = "config")
    val config: ScanConfigResponse? = null,

    @SerialName(value = "score")
    val score: ScoreResponse? = null

) {


}

