/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Per-repository metrics snapshot.
 *
 * @param artifactCount 
 * @param downloadCount 
 * @param repositoryId 
 * @param snapshotDate 
 * @param storageBytes 
 * @param repositoryKey 
 * @param repositoryName 
 */
@Serializable

data class RepositorySnapshot (

    @SerialName(value = "artifact_count")
    val artifactCount: kotlin.Long,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @Contextual @SerialName(value = "snapshot_date")
    val snapshotDate: java.time.LocalDate,

    @SerialName(value = "storage_bytes")
    val storageBytes: kotlin.Long,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String? = null,

    @SerialName(value = "repository_name")
    val repositoryName: kotlin.String? = null

) {


}

