/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Repository signing configuration.
 *
 * @param createdAt 
 * @param id 
 * @param repositoryId 
 * @param requireSignatures 
 * @param signMetadata 
 * @param signPackages 
 * @param updatedAt 
 * @param signingKeyId 
 */
@Serializable

data class RepositorySigningConfig (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "require_signatures")
    val requireSignatures: kotlin.Boolean,

    @SerialName(value = "sign_metadata")
    val signMetadata: kotlin.Boolean,

    @SerialName(value = "sign_packages")
    val signPackages: kotlin.Boolean,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "signing_key_id")
    val signingKeyId: java.util.UUID? = null

) {


}

