/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactsEvaluated 
 * @param artifactsFailing 
 * @param artifactsPassing 
 * @param healthGrade 
 * @param healthScore 
 * @param repositoryId 
 * @param repositoryKey 
 * @param avgLicenseScore 
 * @param avgMetadataScore 
 * @param avgQualityScore 
 * @param avgSecurityScore 
 * @param lastEvaluatedAt 
 */
@Serializable

data class RepoHealthResponse (

    @SerialName(value = "artifacts_evaluated")
    val artifactsEvaluated: kotlin.Int,

    @SerialName(value = "artifacts_failing")
    val artifactsFailing: kotlin.Int,

    @SerialName(value = "artifacts_passing")
    val artifactsPassing: kotlin.Int,

    @SerialName(value = "health_grade")
    val healthGrade: kotlin.String,

    @SerialName(value = "health_score")
    val healthScore: kotlin.Int,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "avg_license_score")
    val avgLicenseScore: kotlin.Int? = null,

    @SerialName(value = "avg_metadata_score")
    val avgMetadataScore: kotlin.Int? = null,

    @SerialName(value = "avg_quality_score")
    val avgQualityScore: kotlin.Int? = null,

    @SerialName(value = "avg_security_score")
    val avgSecurityScore: kotlin.Int? = null,

    @Contextual @SerialName(value = "last_evaluated_at")
    val lastEvaluatedAt: java.time.OffsetDateTime? = null

) {


}

