/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Current per-repository storage breakdown.
 *
 * @param artifactCount 
 * @param downloadCount 
 * @param format 
 * @param repositoryId 
 * @param repositoryKey 
 * @param repositoryName 
 * @param storageBytes 
 * @param lastUploadAt 
 */
@Serializable

data class RepositoryStorageBreakdown (

    @SerialName(value = "artifact_count")
    val artifactCount: kotlin.Long,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @SerialName(value = "format")
    val format: kotlin.String,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "repository_name")
    val repositoryName: kotlin.String,

    @SerialName(value = "storage_bytes")
    val storageBytes: kotlin.Long,

    @Contextual @SerialName(value = "last_upload_at")
    val lastUploadAt: java.time.OffsetDateTime? = null

) {


}

