/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Summary of a repository-scoped token.
 *
 * @param createdAt 
 * @param id 
 * @param isExpired 
 * @param isRevoked 
 * @param name 
 * @param scopes 
 * @param tokenPrefix 
 * @param createdBy 
 * @param description 
 * @param expiresAt 
 * @param lastUsedAt 
 */
@Serializable

data class RepoTokenResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_expired")
    val isExpired: kotlin.Boolean,

    @SerialName(value = "is_revoked")
    val isRevoked: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "token_prefix")
    val tokenPrefix: kotlin.String,

    @SerialName(value = "created_by")
    val createdBy: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_used_at")
    val lastUsedAt: java.time.OffsetDateTime? = null

) {


}

