/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param matchFormats 
 * @param matchLabels 
 * @param matchPattern 
 * @param matchRepos 
 */
@Serializable

data class RepoSelectorSchema (

    @SerialName(value = "match_formats")
    val matchFormats: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "match_labels")
    val matchLabels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "match_pattern")
    val matchPattern: kotlin.String? = null,

    @SerialName(value = "match_repos")
    val matchRepos: kotlin.collections.List<@Contextual java.util.UUID>? = null

) {


}

