/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param format 
 * @param id 
 * @param isPublic 
 * @param key 
 * @param name 
 * @param repoType 
 * @param storageUsedBytes 
 * @param updatedAt 
 * @param description 
 * @param quotaBytes 
 */
@Serializable

data class RepositoryResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "format")
    val format: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_public")
    val isPublic: kotlin.Boolean,

    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "repo_type")
    val repoType: kotlin.String,

    @SerialName(value = "storage_used_bytes")
    val storageUsedBytes: kotlin.Long,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long? = null

) {


}

