/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactsEnqueued Number of artifacts whose latest scan had no inventory rows and for which a rescan was enqueued in this call.
 * @param limit Echo of the requested (or defaulted) limit, useful for clients driving the loop programmatically.
 */
@Serializable

data class RescanForInventoryResponse (

    /* Number of artifacts whose latest scan had no inventory rows and for which a rescan was enqueued in this call. */
    @SerialName(value = "artifacts_enqueued")
    val artifactsEnqueued: kotlin.Long,

    /* Echo of the requested (or defaulted) limit, useful for clients driving the loop programmatically. */
    @SerialName(value = "limit")
    val limit: kotlin.Long

) {


}

