/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param limit Maximum number of artifacts to enqueue in this call. Operators run the endpoint repeatedly to drain large backfills without stalling a single HTTP worker; the handler returns the actual number enqueued so the caller can detect when work is done. Defaults to 100. Hard-capped at 1000 to avoid pathological inputs.
 */
@Serializable

data class RescanForInventoryRequest (

    /* Maximum number of artifacts to enqueue in this call. Operators run the endpoint repeatedly to drain large backfills without stalling a single HTTP worker; the handler returns the actual number enqueued so the caller can detect when work is done. Defaults to 100. Hard-capped at 1000 to avoid pathological inputs. */
    @SerialName(value = "limit")
    val limit: kotlin.Long? = null

) {


}

