/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactsRestored 
 * @param errors 
 * @param tablesRestored 
 */
@Serializable

data class RestoreResponse (

    @SerialName(value = "artifacts_restored")
    val artifactsRestored: kotlin.Int,

    @SerialName(value = "errors")
    val errors: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "tables_restored")
    val tablesRestored: kotlin.collections.List<kotlin.String>

) {


}

