/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param restoreArtifacts 
 * @param restoreDatabase 
 * @param targetRepositoryId 
 */
@Serializable

data class RestoreRequest (

    @SerialName(value = "restore_artifacts")
    val restoreArtifacts: kotlin.Boolean? = null,

    @SerialName(value = "restore_database")
    val restoreDatabase: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "target_repository_id")
    val targetRepositoryId: java.util.UUID? = null

) {


}

