/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response returned by the rotate-secret endpoint.
 *
 * @param id 
 * @param previousSecretExpiresAt When the previously active secret stops being accepted.
 * @param secret Raw signing secret produced by this rotation. Shown exactly once.
 * @param secretDigest 
 */
@Serializable

data class RotateWebhookSecretResponse (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* When the previously active secret stops being accepted. */
    @Contextual @SerialName(value = "previous_secret_expires_at")
    val previousSecretExpiresAt: java.time.OffsetDateTime,

    /* Raw signing secret produced by this rotation. Shown exactly once. */
    @SerialName(value = "secret")
    val secret: kotlin.String,

    @SerialName(value = "secret_digest")
    val secretDigest: kotlin.String

) {


}

