/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single routing rule that maps an incoming path to a rewritten path.
 *
 * @param pathPattern Regex pattern matched against the full request path. Use capture groups to extract portions for the rewrite template.
 * @param rewriteTo Rewrite template. Use `$1`, `$2`, etc. to reference captured groups from `path_pattern`.
 */
@Serializable

data class RoutingRule (

    /* Regex pattern matched against the full request path. Use capture groups to extract portions for the rewrite template. */
    @SerialName(value = "path_pattern")
    val pathPattern: kotlin.String,

    /* Rewrite template. Use `$1`, `$2`, etc. to reference captured groups from `path_pattern`. */
    @SerialName(value = "rewrite_to")
    val rewriteTo: kotlin.String

) {


}

