/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param passed 
 * @param ruleId 
 * @param ruleName 
 * @param violations 
 */
@Serializable

data class RuleEvaluationResponse (

    @SerialName(value = "passed")
    val passed: kotlin.Boolean,

    @Contextual @SerialName(value = "rule_id")
    val ruleId: java.util.UUID,

    @SerialName(value = "rule_name")
    val ruleName: kotlin.String,

    @SerialName(value = "violations")
    val violations: kotlin.collections.List<kotlin.String>

) {


}

