/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param action 
 * @param architecture 
 * @param createdAt 
 * @param enabled 
 * @param id 
 * @param packagePattern 
 * @param priority 
 * @param reason 
 * @param updatedAt 
 * @param versionConstraint 
 * @param createdBy 
 * @param stagingRepoId 
 */
@Serializable

data class RuleResponse (

    @SerialName(value = "action")
    val action: kotlin.String,

    @SerialName(value = "architecture")
    val architecture: kotlin.String,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "package_pattern")
    val packagePattern: kotlin.String,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @SerialName(value = "reason")
    val reason: kotlin.String,

    @SerialName(value = "updated_at")
    val updatedAt: kotlin.String,

    @SerialName(value = "version_constraint")
    val versionConstraint: kotlin.String,

    @Contextual @SerialName(value = "created_by")
    val createdBy: java.util.UUID? = null,

    @Contextual @SerialName(value = "staging_repo_id")
    val stagingRepoId: java.util.UUID? = null

) {


}

