/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attributeMapping 
 * @param createdAt 
 * @param entityId 
 * @param hasCertificate 
 * @param id 
 * @param isEnabled 
 * @param name 
 * @param nameIdFormat 
 * @param requireSignedAssertions 
 * @param signRequests 
 * @param spEntityId 
 * @param ssoUrl 
 * @param updatedAt 
 * @param adminGroup 
 * @param sloUrl 
 */
@Serializable

data class SamlConfigResponse (

    @Contextual @SerialName(value = "attribute_mapping")
    val attributeMapping: kotlinx.serialization.json.JsonElement,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "entity_id")
    val entityId: kotlin.String,

    @SerialName(value = "has_certificate")
    val hasCertificate: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "name_id_format")
    val nameIdFormat: kotlin.String,

    @SerialName(value = "require_signed_assertions")
    val requireSignedAssertions: kotlin.Boolean,

    @SerialName(value = "sign_requests")
    val signRequests: kotlin.Boolean,

    @SerialName(value = "sp_entity_id")
    val spEntityId: kotlin.String,

    @SerialName(value = "sso_url")
    val ssoUrl: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "admin_group")
    val adminGroup: kotlin.String? = null,

    @SerialName(value = "slo_url")
    val sloUrl: kotlin.String? = null

) {


}

