/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Scanner availability flags.
 *
 * @param dependencyTrackEnabled Whether the Dependency-Track integration is configured.
 * @param openscapEnabled Whether the OpenSCAP compliance scanner is configured.
 * @param trivyEnabled Whether the Trivy vulnerability scanner is configured.
 */
@Serializable

data class ScannersConfig (

    /* Whether the Dependency-Track integration is configured. */
    @SerialName(value = "dependency_track_enabled")
    val dependencyTrackEnabled: kotlin.Boolean,

    /* Whether the OpenSCAP compliance scanner is configured. */
    @SerialName(value = "openscap_enabled")
    val openscapEnabled: kotlin.Boolean,

    /* Whether the Trivy vulnerability scanner is configured. */
    @SerialName(value = "trivy_enabled")
    val trivyEnabled: kotlin.Boolean

) {


}

