/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockOnPolicyViolation 
 * @param createdAt 
 * @param id 
 * @param repositoryId 
 * @param scanEnabled 
 * @param scanOnProxy 
 * @param scanOnUpload 
 * @param severityThreshold 
 * @param updatedAt 
 */
@Serializable

data class ScanConfigResponse (

    @SerialName(value = "block_on_policy_violation")
    val blockOnPolicyViolation: kotlin.Boolean,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "scan_enabled")
    val scanEnabled: kotlin.Boolean,

    @SerialName(value = "scan_on_proxy")
    val scanOnProxy: kotlin.Boolean,

    @SerialName(value = "scan_on_upload")
    val scanOnUpload: kotlin.Boolean,

    @SerialName(value = "severity_threshold")
    val severityThreshold: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

