/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param createdAt 
 * @param criticalCount 
 * @param findingsCount 
 * @param highCount 
 * @param id 
 * @param infoCount 
 * @param isReused True when the row was synthesized by the dedup path (`copy_scan_results`) because a prior scan with the same `(checksum_sha256, scan_type)` pair already existed within the dedup TTL. No scanner was actually invoked for this row; counts and findings were copied from `source_scan_id`.
 * @param lowCount 
 * @param mediumCount 
 * @param repositoryId 
 * @param scanType 
 * @param status 
 * @param artifactName 
 * @param artifactVersion 
 * @param completedAt 
 * @param errorMessage 
 * @param scannerVersion 
 * @param sourceScanId When `is_reused` is true, the `id` of the source scan whose results were copied. Useful for distinguishing \"fresh scan\" from \"deduped satisfaction\" in release-gate provenance checks. None for original (non-reused) scans.
 * @param startedAt 
 */
@Serializable

data class ScanResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "critical_count")
    val criticalCount: kotlin.Int,

    @SerialName(value = "findings_count")
    val findingsCount: kotlin.Int,

    @SerialName(value = "high_count")
    val highCount: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "info_count")
    val infoCount: kotlin.Int,

    /* True when the row was synthesized by the dedup path (`copy_scan_results`) because a prior scan with the same `(checksum_sha256, scan_type)` pair already existed within the dedup TTL. No scanner was actually invoked for this row; counts and findings were copied from `source_scan_id`. */
    @SerialName(value = "is_reused")
    val isReused: kotlin.Boolean,

    @SerialName(value = "low_count")
    val lowCount: kotlin.Int,

    @SerialName(value = "medium_count")
    val mediumCount: kotlin.Int,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "scan_type")
    val scanType: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "artifact_name")
    val artifactName: kotlin.String? = null,

    @SerialName(value = "artifact_version")
    val artifactVersion: kotlin.String? = null,

    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "error_message")
    val errorMessage: kotlin.String? = null,

    @SerialName(value = "scanner_version")
    val scannerVersion: kotlin.String? = null,

    /* When `is_reused` is true, the `id` of the source scan whose results were copied. Useful for distinguishing \"fresh scan\" from \"deduped satisfaction\" in release-gate provenance checks. None for original (non-reused) scans. */
    @Contextual @SerialName(value = "source_scan_id")
    val sourceScanId: java.util.UUID? = null,

    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null

) {


}

