/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param acknowledgedCount 
 * @param calculatedAt 
 * @param criticalCount 
 * @param grade 
 * @param highCount 
 * @param id 
 * @param lowCount 
 * @param mediumCount 
 * @param repositoryId 
 * @param score 
 * @param totalFindings 
 * @param lastScanAt 
 */
@Serializable

data class ScoreResponse (

    @SerialName(value = "acknowledged_count")
    val acknowledgedCount: kotlin.Int,

    @Contextual @SerialName(value = "calculated_at")
    val calculatedAt: java.time.OffsetDateTime,

    @SerialName(value = "critical_count")
    val criticalCount: kotlin.Int,

    @SerialName(value = "grade")
    val grade: kotlin.String,

    @SerialName(value = "high_count")
    val highCount: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "low_count")
    val lowCount: kotlin.Int,

    @SerialName(value = "medium_count")
    val mediumCount: kotlin.Int,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "score")
    val score: kotlin.Int,

    @SerialName(value = "total_findings")
    val totalFindings: kotlin.Int,

    @Contextual @SerialName(value = "last_scan_at")
    val lastScanAt: java.time.OffsetDateTime? = null

) {


}

