/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param availableChunks 
 * @param endpointUrl 
 * @param peerId 
 * @param score 
 * @param bandwidthEstimateBps 
 * @param latencyMs 
 */
@Serializable

data class ScoredPeerResponse (

    @SerialName(value = "available_chunks")
    val availableChunks: kotlin.Int,

    @SerialName(value = "endpoint_url")
    val endpointUrl: kotlin.String,

    @Contextual @SerialName(value = "peer_id")
    val peerId: java.util.UUID,

    @SerialName(value = "score")
    val score: kotlin.Double,

    @SerialName(value = "bandwidth_estimate_bps")
    val bandwidthEstimateBps: kotlin.Long? = null,

    @SerialName(value = "latency_ms")
    val latencyMs: kotlin.Int? = null

) {


}

