/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A unified search result matching the frontend `SearchResult` interface.
 *
 * @param createdAt 
 * @param id 
 * @param name 
 * @param repositoryKey 
 * @param type 
 * @param format 
 * @param highlights 
 * @param path 
 * @param sizeBytes 
 * @param version 
 */
@Serializable

data class SearchResultItem (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "format")
    val format: kotlin.String? = null,

    @SerialName(value = "highlights")
    val highlights: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "path")
    val path: kotlin.String? = null,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long? = null,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

