/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactPath 
 * @param bytesReceived 
 * @param chunksCompleted 
 * @param chunksTotal 
 * @param createdAt 
 * @param expiresAt 
 * @param repositoryKey 
 * @param sessionId 
 * @param status 
 * @param totalSize 
 */
@Serializable

data class SessionStatusResponse (

    @SerialName(value = "artifact_path")
    val artifactPath: kotlin.String,

    @SerialName(value = "bytes_received")
    val bytesReceived: kotlin.Long,

    @SerialName(value = "chunks_completed")
    val chunksCompleted: kotlin.Int,

    @SerialName(value = "chunks_total")
    val chunksTotal: kotlin.Int,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String,

    @SerialName(value = "expires_at")
    val expiresAt: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @Contextual @SerialName(value = "session_id")
    val sessionId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "total_size")
    val totalSize: kotlin.Long

) {


}

