/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.PeerLabelEntrySchema

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param labels 
 */
@Serializable

data class SetPeerLabelsRequest (

    @SerialName(value = "labels")
    val labels: kotlin.collections.List<PeerLabelEntrySchema>

) {


}

