/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param releaseRepositoryKey Repository key of the release (local) repository to link. Pass `null` or omit to remove the link.
 */
@Serializable

data class SetReleaseTargetRequest (

    /* Repository key of the release (local) repository to link. Pass `null` or omit to remove the link. */
    @SerialName(value = "release_repository_key")
    val releaseRepositoryKey: kotlin.String? = null

) {


}

