/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.RoutingRule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param rules Ordered list of routing rules. Each rule specifies a regex pattern and a rewrite template. Rules are evaluated in order during proxy requests.
 */
@Serializable

data class SetRoutingRulesRequest (

    /* Ordered list of routing rules. Each rule specifies a regex pattern and a rewrite template. Rules are evaluated in order during proxy requests. */
    @SerialName(value = "rules")
    val rules: kotlin.collections.List<RoutingRule>

) {


}

