/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response body for the setup status endpoint.
 *
 * @param setupRequired Whether the initial admin password change is still required.
 */
@Serializable

data class SetupStatusResponse (

    /* Whether the initial admin password change is still required. */
    @SerialName(value = "setup_required")
    val setupRequired: kotlin.Boolean

) {


}

