/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Public view of a signing key (no private material).
 *
 * @param algorithm 
 * @param createdAt 
 * @param id 
 * @param isActive 
 * @param keyType 
 * @param name 
 * @param publicKeyPem 
 * @param expiresAt 
 * @param fingerprint 
 * @param keyId 
 * @param lastUsedAt 
 * @param repositoryId 
 * @param uidEmail 
 * @param uidName 
 */
@Serializable

data class SigningKeyPublic (

    @SerialName(value = "algorithm")
    val algorithm: kotlin.String,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean,

    @SerialName(value = "key_type")
    val keyType: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "public_key_pem")
    val publicKeyPem: kotlin.String,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "fingerprint")
    val fingerprint: kotlin.String? = null,

    @SerialName(value = "key_id")
    val keyId: kotlin.String? = null,

    @Contextual @SerialName(value = "last_used_at")
    val lastUsedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null,

    @SerialName(value = "uid_email")
    val uidEmail: kotlin.String? = null,

    @SerialName(value = "uid_name")
    val uidName: kotlin.String? = null

) {


}

