/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body for the SMTP test endpoint.
 *
 * @param to Recipient email address for the test message.  Accepts `recipient` as an alias for backward compatibility with Web UI versions <= 1.1.3, which send `{\"recipient\": \"...\"}`.
 */
@Serializable

data class SmtpTestRequest (

    /* Recipient email address for the test message.  Accepts `recipient` as an alias for backward compatibility with Web UI versions <= 1.1.3, which send `{\"recipient\": \"...\"}`. */
    @SerialName(value = "to")
    val to: kotlin.String

) {


}

