/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param packageType 
 * @param type 
 * @param url 
 * @param description 
 */
@Serializable

data class SourceRepository (

    @SerialName(value = "key")
    val key: kotlin.String,

    @SerialName(value = "package_type")
    val packageType: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String? = null

) {


}

