/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param loginUrl 
 * @param name 
 * @param providerType 
 */
@Serializable

data class SsoProviderInfo (

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "login_url")
    val loginUrl: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "provider_type")
    val providerType: kotlin.String

) {


}

