/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Artifact aging report entry.
 *
 * @param artifactId 
 * @param createdAt 
 * @param daysSinceDownload 
 * @param downloadCount 
 * @param name 
 * @param path 
 * @param repositoryKey 
 * @param sizeBytes 
 * @param lastDownloadedAt 
 */
@Serializable

data class StaleArtifact (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "days_since_download")
    val daysSinceDownload: kotlin.Long,

    @SerialName(value = "download_count")
    val downloadCount: kotlin.Long,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @Contextual @SerialName(value = "last_downloaded_at")
    val lastDownloadedAt: java.time.OffsetDateTime? = null

) {


}

