/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A single day's storage metrics snapshot.
 *
 * @param snapshotDate 
 * @param totalArtifacts 
 * @param totalDownloads 
 * @param totalRepositories 
 * @param totalStorageBytes 
 * @param totalUsers 
 */
@Serializable

data class StorageSnapshot (

    @Contextual @SerialName(value = "snapshot_date")
    val snapshotDate: java.time.LocalDate,

    @SerialName(value = "total_artifacts")
    val totalArtifacts: kotlin.Long,

    @SerialName(value = "total_downloads")
    val totalDownloads: kotlin.Long,

    @SerialName(value = "total_repositories")
    val totalRepositories: kotlin.Long,

    @SerialName(value = "total_storage_bytes")
    val totalStorageBytes: kotlin.Long,

    @SerialName(value = "total_users")
    val totalUsers: kotlin.Long

) {


}

