/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request body for storage GC.
 *
 * @param dryRun When true, report what would be deleted without actually deleting.
 */
@Serializable

data class StorageGcRequest (

    /* When true, report what would be deleted without actually deleting. */
    @SerialName(value = "dry_run")
    val dryRun: kotlin.Boolean? = null

) {


}

