/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Detailed subscription view (mode, schedule, filter) for a single (peer, repo) pair.
 *
 * @param createdAt 
 * @param id 
 * @param peerInstanceId 
 * @param replicationFilter 
 * @param repositoryId 
 * @param syncEnabled 
 * @param lastReplicatedAt 
 * @param replicationMode 
 * @param replicationSchedule 
 */
@Serializable

data class SubscriptionResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "peer_instance_id")
    val peerInstanceId: java.util.UUID,

    @Contextual @SerialName(value = "replication_filter")
    val replicationFilter: kotlin.Any,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID,

    @SerialName(value = "sync_enabled")
    val syncEnabled: kotlin.Boolean,

    @Contextual @SerialName(value = "last_replicated_at")
    val lastReplicatedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String? = null,

    @SerialName(value = "replication_schedule")
    val replicationSchedule: kotlin.String? = null

) {


}

