/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param serviceName 
 * @param until 
 */
@Serializable

data class SuppressRequest (

    @SerialName(value = "service_name")
    val serviceName: kotlin.String,

    @Contextual @SerialName(value = "until")
    val until: java.time.OffsetDateTime

) {


}

