/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param artifactSize 
 * @param createdAt When the task was enqueued. Lets clients tell a freshly-scheduled task apart from a stale queue entry (used by the replication-schedule check). Serialized as whole-second RFC3339 with a `Z` suffix (e.g. `2026-05-29T12:34:56Z`) so simple ISO8601 parsers can consume it.
 * @param id 
 * @param priority 
 * @param status Task status (e.g. \"pending\"). Listing currently returns pending tasks.
 * @param storageKey 
 * @param startedAt When the worker began transferring, if it has started. Same format as `created_at`.
 */
@Serializable

data class SyncTaskResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "artifact_size")
    val artifactSize: kotlin.Long,

    /* When the task was enqueued. Lets clients tell a freshly-scheduled task apart from a stale queue entry (used by the replication-schedule check). Serialized as whole-second RFC3339 with a `Z` suffix (e.g. `2026-05-29T12:34:56Z`) so simple ISO8601 parsers can consume it. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    /* Task status (e.g. \"pending\"). Listing currently returns pending tasks. */
    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "storage_key")
    val storageKey: kotlin.String,

    /* When the worker began transferring, if it has started. Same format as `created_at`. */
    @Contextual @SerialName(value = "started_at")
    val startedAt: java.time.OffsetDateTime? = null

) {


}

