/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactFilter 
 * @param createdAt 
 * @param description 
 * @param enabled 
 * @param filter Convenience glob filter, mirrored from `artifact_filter.include_paths`. Round-trips the single-pattern shorthand accepted on create (e.g. `\"*.tar.gz\"`). Empty when no include pattern is set.
 * @param id 
 * @param name 
 * @param peerSelector 
 * @param precedence 
 * @param priority 
 * @param replicationMode 
 * @param repoSelector 
 * @param updatedAt 
 */
@Serializable

data class SyncPolicyResponse (

    @Contextual @SerialName(value = "artifact_filter")
    val artifactFilter: kotlin.Any,

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "description")
    val description: kotlin.String,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    /* Convenience glob filter, mirrored from `artifact_filter.include_paths`. Round-trips the single-pattern shorthand accepted on create (e.g. `\"*.tar.gz\"`). Empty when no include pattern is set. */
    @SerialName(value = "filter")
    val filter: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "peer_selector")
    val peerSelector: kotlin.Any,

    @SerialName(value = "precedence")
    val precedence: kotlin.Int,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @SerialName(value = "replication_mode")
    val replicationMode: kotlin.String,

    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlin.Any,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

