/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactId 
 * @param artifactSize 
 * @param id 
 * @param priority 
 * @param storageKey 
 */
@Serializable

data class SyncTaskResponse (

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "artifact_size")
    val artifactSize: kotlin.Long,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "priority")
    val priority: kotlin.Int,

    @SerialName(value = "storage_key")
    val storageKey: kotlin.String

) {


}

