/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowAnonymousDownload 
 * @param auditRetentionDays 
 * @param backupRetentionCount 
 * @param edgeStaleThresholdMinutes 
 * @param maxUploadSizeBytes 
 * @param retentionDays 
 */
@Serializable

data class SystemSettings (

    @SerialName(value = "allow_anonymous_download")
    val allowAnonymousDownload: kotlin.Boolean,

    @SerialName(value = "audit_retention_days")
    val auditRetentionDays: kotlin.Int,

    @SerialName(value = "backup_retention_count")
    val backupRetentionCount: kotlin.Int,

    @SerialName(value = "edge_stale_threshold_minutes")
    val edgeStaleThresholdMinutes: kotlin.Int,

    @SerialName(value = "max_upload_size_bytes")
    val maxUploadSizeBytes: kotlin.Long,

    @SerialName(value = "retention_days")
    val retentionDays: kotlin.Int

) {


}

