/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.AuthConfig
import com.artifactkeeper.client.models.PermissionsConfig
import com.artifactkeeper.client.models.PluginSigningConfig
import com.artifactkeeper.client.models.ScannersConfig

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Public runtime configuration values.  This response intentionally omits all secrets, credentials, and internal connection strings. Only values useful for UI/client behavior are included.
 *
 * @param auth Authentication provider availability.
 * @param demoMode Whether the instance is running in demo mode (writes blocked).
 * @param guestAccessEnabled Whether anonymous (unauthenticated) access is permitted at all (issue #850). When `false`, the server rejects all unauthenticated requests except for the login, setup, health, and OCI challenge endpoints. Frontends should hide UI affordances that imply public access (e.g. the \"public repo\" toggle) and redirect unauthenticated users to the login page.
 * @param maxUploadSizeBytes Maximum upload size in bytes (0 means no limit).
 * @param permissions Fine-grained permissions enforcement status. Permission rules can be managed via /api/v1/permissions and are actively enforced.
 * @param pluginSigning Plugin signature-verification (supply-chain) policy status.
 * @param scanners Scanner availability.
 * @param searchEngine Search engine type: \"opensearch\" when configured, \"database\" otherwise.
 * @param storageBackend Storage backend type (e.g. \"filesystem\", \"s3\", \"gcs\", \"azure\").
 * @param oidcIssuer OIDC issuer URL, if configured. This is public information needed by clients to initiate the OIDC flow.
 */
@Serializable

data class SystemConfigResponse (

    /* Authentication provider availability. */
    @SerialName(value = "auth")
    val auth: AuthConfig,

    /* Whether the instance is running in demo mode (writes blocked). */
    @SerialName(value = "demo_mode")
    val demoMode: kotlin.Boolean,

    /* Whether anonymous (unauthenticated) access is permitted at all (issue #850). When `false`, the server rejects all unauthenticated requests except for the login, setup, health, and OCI challenge endpoints. Frontends should hide UI affordances that imply public access (e.g. the \"public repo\" toggle) and redirect unauthenticated users to the login page. */
    @SerialName(value = "guest_access_enabled")
    val guestAccessEnabled: kotlin.Boolean,

    /* Maximum upload size in bytes (0 means no limit). */
    @SerialName(value = "max_upload_size_bytes")
    val maxUploadSizeBytes: kotlin.Long,

    /* Fine-grained permissions enforcement status. Permission rules can be managed via /api/v1/permissions and are actively enforced. */
    @SerialName(value = "permissions")
    val permissions: PermissionsConfig,

    /* Plugin signature-verification (supply-chain) policy status. */
    @SerialName(value = "plugin_signing")
    val pluginSigning: PluginSigningConfig,

    /* Scanner availability. */
    @SerialName(value = "scanners")
    val scanners: ScannersConfig,

    /* Search engine type: \"opensearch\" when configured, \"database\" otherwise. */
    @SerialName(value = "search_engine")
    val searchEngine: kotlin.String,

    /* Storage backend type (e.g. \"filesystem\", \"s3\", \"gcs\", \"azure\"). */
    @SerialName(value = "storage_backend")
    val storageBackend: kotlin.String,

    /* OIDC issuer URL, if configured. This is public information needed by clients to initiate the OIDC flow. */
    @SerialName(value = "oidc_issuer")
    val oidcIssuer: kotlin.String? = null

) {


}

