/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Telemetry configuration.
 *
 * @param enabled 
 * @param includeLogs 
 * @param reviewBeforeSend 
 * @param scrubLevel 
 */
@Serializable

data class TelemetrySettings (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "include_logs")
    val includeLogs: kotlin.Boolean,

    @SerialName(value = "review_before_send")
    val reviewBeforeSend: kotlin.Boolean,

    @SerialName(value = "scrub_level")
    val scrubLevel: kotlin.String

) {


}

