/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request for testing a format handler
 *
 * @param content Base64-encoded content to test, or raw string content
 * @param path Path to simulate for the artifact
 * @param base64 Whether content is base64 encoded
 */
@Serializable

data class TestFormatRequest (

    /* Base64-encoded content to test, or raw string content */
    @SerialName(value = "content")
    val content: kotlin.String,

    /* Path to simulate for the artifact */
    @SerialName(value = "path")
    val path: kotlin.String,

    /* Whether content is base64 encoded */
    @SerialName(value = "base64")
    val base64: kotlin.Boolean? = null

) {


}

