/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Metadata returned from testing
 *
 * @param contentType 
 * @param path 
 * @param sizeBytes 
 * @param version 
 */
@Serializable

data class TestMetadata (

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "version")
    val version: kotlin.String? = null

) {


}

