/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.TestMetadata

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response from format handler test
 *
 * @param valid Whether validation passed
 * @param metadata Parsed metadata if parse_metadata succeeded
 * @param parseError Parse error message if any
 * @param validationError Validation error message if any
 */
@Serializable

data class TestFormatResponse (

    /* Whether validation passed */
    @SerialName(value = "valid")
    val valid: kotlin.Boolean,

    /* Parsed metadata if parse_metadata succeeded */
    @SerialName(value = "metadata")
    val metadata: TestMetadata? = null,

    /* Parse error message if any */
    @SerialName(value = "parse_error")
    val parseError: kotlin.String? = null,

    /* Validation error message if any */
    @SerialName(value = "validation_error")
    val validationError: kotlin.String? = null

) {


}

