/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param error 
 * @param responseBody 
 * @param statusCode 
 */
@Serializable

data class TestWebhookResponse (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "error")
    val error: kotlin.String? = null,

    @SerialName(value = "response_body")
    val responseBody: kotlin.String? = null,

    @SerialName(value = "status_code")
    val statusCode: kotlin.Int? = null

) {


}

