/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param isExpired 
 * @param name 
 * @param repositoryIds Explicit repository IDs this token is restricted to (from join table).
 * @param scopes 
 * @param tokenPrefix 
 * @param expiresAt 
 * @param lastUsedAt 
 * @param repoSelector Dynamic repository selector, if configured.
 */
@Serializable

data class TokenInfoResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_expired")
    val isExpired: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    /* Explicit repository IDs this token is restricted to (from join table). */
    @SerialName(value = "repository_ids")
    val repositoryIds: kotlin.collections.List<@Contextual java.util.UUID>,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "token_prefix")
    val tokenPrefix: kotlin.String,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_used_at")
    val lastUsedAt: java.time.OffsetDateTime? = null,

    /* Dynamic repository selector, if configured. */
    @Contextual @SerialName(value = "repo_selector")
    val repoSelector: kotlin.Any? = null

) {


}

