/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactChecksum 
 * @param artifactId 
 * @param checksumAlgo 
 * @param chunkSize 
 * @param completedChunks 
 * @param id 
 * @param requestingPeerId 
 * @param status 
 * @param totalChunks 
 * @param totalSize 
 */
@Serializable

data class TransferSessionResponse (

    @SerialName(value = "artifact_checksum")
    val artifactChecksum: kotlin.String,

    @Contextual @SerialName(value = "artifact_id")
    val artifactId: java.util.UUID,

    @SerialName(value = "checksum_algo")
    val checksumAlgo: kotlin.String,

    @SerialName(value = "chunk_size")
    val chunkSize: kotlin.Int,

    @SerialName(value = "completed_chunks")
    val completedChunks: kotlin.Int,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "requesting_peer_id")
    val requestingPeerId: java.util.UUID,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "total_chunks")
    val totalChunks: kotlin.Int,

    @SerialName(value = "total_size")
    val totalSize: kotlin.Long

) {


}

