/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param hasChildren 
 * @param id 
 * @param name 
 * @param path 
 * @param type 
 * @param childrenCount 
 * @param createdAt 
 * @param repositoryKey 
 * @param sizeBytes 
 */
@Serializable

data class TreeNodeResponse (

    @SerialName(value = "has_children")
    val hasChildren: kotlin.Boolean,

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "path")
    val path: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "children_count")
    val childrenCount: kotlin.Long? = null,

    @SerialName(value = "created_at")
    val createdAt: kotlin.String? = null,

    @SerialName(value = "repository_key")
    val repositoryKey: kotlin.String? = null,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long? = null

) {


}

