/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param artifactsQueued 
 * @param message 
 */
@Serializable

data class TriggerScanResponse (

    @SerialName(value = "artifacts_queued")
    val artifactsQueued: kotlin.Int,

    @SerialName(value = "message")
    val message: kotlin.String

) {


}

