/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status 
 * @param reason 
 */
@Serializable

data class UpdateCveStatusRequest (

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "reason")
    val reason: kotlin.String? = null

) {


}

