/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param description 
 * @param isPublic 
 * @param name 
 * @param quotaBytes 
 */
@Serializable

data class UpdateRepositoryRequest (

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "is_public")
    val isPublic: kotlin.Boolean? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long? = null

) {


}

