/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param blockOnFail 
 * @param blockUnscanned 
 * @param isEnabled 
 * @param maxSeverity 
 * @param name 
 * @param maxArtifactAgeDays 
 * @param minStagingHours 
 * @param requireSignature 
 */
@Serializable

data class UpdatePolicyRequest (

    @SerialName(value = "block_on_fail")
    val blockOnFail: kotlin.Boolean,

    @SerialName(value = "block_unscanned")
    val blockUnscanned: kotlin.Boolean,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "max_severity")
    val maxSeverity: kotlin.String,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "max_artifact_age_days")
    val maxArtifactAgeDays: kotlin.Int? = null,

    @SerialName(value = "min_staging_hours")
    val minStagingHours: kotlin.Int? = null,

    @SerialName(value = "require_signature")
    val requireSignature: kotlin.Boolean? = null

) {


}

