/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param chunkBitmap 
 * @param totalChunks 
 */
@Serializable

data class UpdateChunkAvailabilityBody (

    @SerialName(value = "chunk_bitmap")
    val chunkBitmap: kotlin.collections.List<kotlin.Int>,

    @SerialName(value = "total_chunks")
    val totalChunks: kotlin.Int

) {


}

