/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param attributeMapping 
 * @param autoCreateUsers 
 * @param clientId 
 * @param clientSecret 
 * @param isEnabled 
 * @param issuerUrl 
 * @param name 
 * @param scopes 
 */
@Serializable

data class UpdateOidcConfigRequest (

    @Contextual @SerialName(value = "attribute_mapping")
    val attributeMapping: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "auto_create_users")
    val autoCreateUsers: kotlin.Boolean? = null,

    @SerialName(value = "client_id")
    val clientId: kotlin.String? = null,

    @SerialName(value = "client_secret")
    val clientSecret: kotlin.String? = null,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @SerialName(value = "issuer_url")
    val issuerUrl: kotlin.String? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>? = null

) {


}

