/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param requireSignatures 
 * @param signMetadata 
 * @param signPackages 
 * @param signingKeyId 
 */
@Serializable

data class UpdateSigningConfigPayload (

    @SerialName(value = "require_signatures")
    val requireSignatures: kotlin.Boolean? = null,

    @SerialName(value = "sign_metadata")
    val signMetadata: kotlin.Boolean? = null,

    @SerialName(value = "sign_packages")
    val signPackages: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "signing_key_id")
    val signingKeyId: java.util.UUID? = null

) {


}

