/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param componentUuid 
 * @param projectUuid 
 * @param state 
 * @param vulnerabilityUuid 
 * @param details 
 * @param justification 
 * @param suppressed 
 */
@Serializable

data class UpdateAnalysisBody (

    @SerialName(value = "component_uuid")
    val componentUuid: kotlin.String,

    @SerialName(value = "project_uuid")
    val projectUuid: kotlin.String,

    @SerialName(value = "state")
    val state: kotlin.String,

    @SerialName(value = "vulnerability_uuid")
    val vulnerabilityUuid: kotlin.String,

    @SerialName(value = "details")
    val details: kotlin.String? = null,

    @SerialName(value = "justification")
    val justification: kotlin.String? = null,

    @SerialName(value = "suppressed")
    val suppressed: kotlin.Boolean? = null

) {


}

