/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param displayName 
 * @param email 
 * @param isActive 
 * @param isAdmin 
 */
@Serializable

data class UpdateUserRequest (

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean? = null,

    @SerialName(value = "is_admin")
    val isAdmin: kotlin.Boolean? = null

) {


}

