/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Request to create or update a scan configuration.
 *
 * @param blockOnPolicyViolation 
 * @param scanEnabled 
 * @param scanOnProxy 
 * @param scanOnUpload 
 * @param severityThreshold 
 */
@Serializable

data class UpsertScanConfigRequest (

    @SerialName(value = "block_on_policy_violation")
    val blockOnPolicyViolation: kotlin.Boolean,

    @SerialName(value = "scan_enabled")
    val scanEnabled: kotlin.Boolean,

    @SerialName(value = "scan_on_proxy")
    val scanOnProxy: kotlin.Boolean,

    @SerialName(value = "scan_on_upload")
    val scanOnUpload: kotlin.Boolean,

    @SerialName(value = "severity_threshold")
    val severityThreshold: kotlin.String

) {


}

