/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param allowedLicenses 
 * @param deniedLicenses 
 * @param name 
 * @param action 
 * @param allowUnknown 
 * @param description 
 * @param isEnabled 
 * @param repositoryId 
 */
@Serializable

data class UpsertLicensePolicyRequest (

    @SerialName(value = "allowed_licenses")
    val allowedLicenses: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "denied_licenses")
    val deniedLicenses: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "action")
    val action: kotlin.String? = null,

    @SerialName(value = "allow_unknown")
    val allowUnknown: kotlin.Boolean? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

