/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authType Auth type: \"basic\", \"bearer\", or \"none\" to remove.
 * @param password Password (basic) or token (bearer). Write-only, never returned.
 * @param username Username for basic auth.
 */
@Serializable

data class UpstreamAuthRequest (

    /* Auth type: \"basic\", \"bearer\", or \"none\" to remove. */
    @SerialName(value = "auth_type")
    val authType: kotlin.String,

    /* Password (basic) or token (bearer). Write-only, never returned. */
    @SerialName(value = "password")
    val password: kotlin.String? = null,

    /* Username for basic auth. */
    @SerialName(value = "username")
    val username: kotlin.String? = null

) {


}

