/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param id 
 * @param isAdmin 
 * @param totpEnabled 
 * @param username 
 * @param displayName 
 */
@Serializable

data class UserResponse (

    @SerialName(value = "email")
    val email: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_admin")
    val isAdmin: kotlin.Boolean,

    @SerialName(value = "totp_enabled")
    val totpEnabled: kotlin.Boolean,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

