/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param memberKey 
 * @param priority 
 */
@Serializable

data class VirtualMemberPriority (

    @SerialName(value = "member_key")
    val memberKey: kotlin.String,

    @SerialName(value = "priority")
    val priority: kotlin.Int

) {


}

