/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param id 
 * @param memberRepoId 
 * @param memberRepoKey 
 * @param memberRepoName 
 * @param memberRepoType 
 * @param priority 
 */
@Serializable

data class VirtualMemberResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "member_repo_id")
    val memberRepoId: java.util.UUID,

    @SerialName(value = "member_repo_key")
    val memberRepoKey: kotlin.String,

    @SerialName(value = "member_repo_name")
    val memberRepoName: kotlin.String,

    @SerialName(value = "member_repo_type")
    val memberRepoType: kotlin.String,

    @SerialName(value = "priority")
    val priority: kotlin.Int

) {


}

