/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * WASM plugin response with extended fields
 *
 * @param capabilities 
 * @param displayName 
 * @param id 
 * @param installedAt 
 * @param name 
 * @param pluginType 
 * @param resourceLimits 
 * @param sourceType 
 * @param status 
 * @param updatedAt 
 * @param version 
 * @param author 
 * @param description 
 * @param enabledAt 
 * @param homepage 
 * @param license 
 * @param sourceRef 
 * @param sourceUrl 
 */
@Serializable

data class WasmPluginResponse (

    @Contextual @SerialName(value = "capabilities")
    val capabilities: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "installed_at")
    val installedAt: java.time.OffsetDateTime,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "plugin_type")
    val pluginType: kotlin.String,

    @Contextual @SerialName(value = "resource_limits")
    val resourceLimits: kotlinx.serialization.json.JsonElement,

    @SerialName(value = "source_type")
    val sourceType: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "author")
    val author: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @Contextual @SerialName(value = "enabled_at")
    val enabledAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "homepage")
    val homepage: kotlin.String? = null,

    @SerialName(value = "license")
    val license: kotlin.String? = null,

    @SerialName(value = "source_ref")
    val sourceRef: kotlin.String? = null,

    @SerialName(value = "source_url")
    val sourceUrl: kotlin.String? = null

) {


}

