/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models

import com.artifactkeeper.client.models.PayloadTemplate

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Response returned exactly once when a webhook is created or its secret is rotated. The raw `secret` value is not retrievable afterwards.
 *
 * @param createdAt 
 * @param eventSchemaVersion Pinned event payload version (e.g. \"2026-04-01\"). Determines the shape of the rendered payload and the value sent in the `X-ArtifactKeeper-Event-Version` header.
 * @param events 
 * @param id 
 * @param isEnabled 
 * @param name 
 * @param payloadTemplate 
 * @param url 
 * @param headers 
 * @param lastTriggeredAt 
 * @param repositoryId 
 * @param secretDigest Short non-reversible identifier for the current signing secret (`whsec_...abcd`), suitable for display in operator UIs. The raw secret is never returned by GET or LIST.
 * @param secretRotationActive True while a previous secret is still accepted by the retry path during a rotation overlap window.
 * @param secret Raw signing secret. Display this to the operator immediately and instruct them to record it; the server retains only the encrypted form and a short digest.  Absent when the webhook was created without a signing secret. This happens when no secret was supplied and the deployment has no `AK_WEBHOOK_SECRET_KEY` configured: rather than fail the create with a 500, the webhook is stored unsigned and deliveries omit the signature header. Configure the key and rotate the secret later to enable signing.
 */
@Serializable

data class WebhookSecretCreatedResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Pinned event payload version (e.g. \"2026-04-01\"). Determines the shape of the rendered payload and the value sent in the `X-ArtifactKeeper-Event-Version` header. */
    @SerialName(value = "event_schema_version")
    val eventSchemaVersion: kotlin.String,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "payload_template")
    val payloadTemplate: PayloadTemplate,

    @SerialName(value = "url")
    val url: kotlin.String,

    @Contextual @SerialName(value = "headers")
    val headers: kotlin.Any? = null,

    @Contextual @SerialName(value = "last_triggered_at")
    val lastTriggeredAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null,

    /* Short non-reversible identifier for the current signing secret (`whsec_...abcd`), suitable for display in operator UIs. The raw secret is never returned by GET or LIST. */
    @SerialName(value = "secret_digest")
    val secretDigest: kotlin.String? = null,

    /* True while a previous secret is still accepted by the retry path during a rotation overlap window. */
    @SerialName(value = "secret_rotation_active")
    val secretRotationActive: kotlin.Boolean? = null,

    /* Raw signing secret. Display this to the operator immediately and instruct them to record it; the server retains only the encrypted form and a short digest.  Absent when the webhook was created without a signing secret. This happens when no secret was supplied and the deployment has no `AK_WEBHOOK_SECRET_KEY` configured: rather than fail the create with a 500, the webhook is stored unsigned and deliveries omit the signature header. Configure the key and rotate the secret later to enable signing. */
    @SerialName(value = "secret")
    val secret: kotlin.String? = null

) {


}

