/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Webhook event types
 *
 * Values: artifact_uploaded,artifact_deleted,repository_created,repository_deleted,user_created,user_deleted,build_started,build_completed,build_failed
 */
@Serializable
enum class WebhookEvent(val value: kotlin.String) {

    @SerialName(value = "artifact_uploaded")
    artifact_uploaded("artifact_uploaded"),

    @SerialName(value = "artifact_deleted")
    artifact_deleted("artifact_deleted"),

    @SerialName(value = "repository_created")
    repository_created("repository_created"),

    @SerialName(value = "repository_deleted")
    repository_deleted("repository_deleted"),

    @SerialName(value = "user_created")
    user_created("user_created"),

    @SerialName(value = "user_deleted")
    user_deleted("user_deleted"),

    @SerialName(value = "build_started")
    build_started("build_started"),

    @SerialName(value = "build_completed")
    build_completed("build_completed"),

    @SerialName(value = "build_failed")
    build_failed("build_failed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WebhookEvent) "$data" else null

        /**
         * Returns a valid [WebhookEvent] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WebhookEvent? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


