/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Webhook event types
 *
 * Values: ARTIFACT_UPLOADED,ARTIFACT_DELETED,REPOSITORY_CREATED,REPOSITORY_DELETED,USER_CREATED,USER_DELETED,BUILD_STARTED,BUILD_COMPLETED,BUILD_FAILED
 */
@Serializable
enum class WebhookEvent(val value: kotlin.String) {

    @SerialName(value = "artifact_uploaded")
    ARTIFACT_UPLOADED("artifact_uploaded"),

    @SerialName(value = "artifact_deleted")
    ARTIFACT_DELETED("artifact_deleted"),

    @SerialName(value = "repository_created")
    REPOSITORY_CREATED("repository_created"),

    @SerialName(value = "repository_deleted")
    REPOSITORY_DELETED("repository_deleted"),

    @SerialName(value = "user_created")
    USER_CREATED("user_created"),

    @SerialName(value = "user_deleted")
    USER_DELETED("user_deleted"),

    @SerialName(value = "build_started")
    BUILD_STARTED("build_started"),

    @SerialName(value = "build_completed")
    BUILD_COMPLETED("build_completed"),

    @SerialName(value = "build_failed")
    BUILD_FAILED("build_failed");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WebhookEvent) "$data" else null

        /**
         * Returns a valid [WebhookEvent] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WebhookEvent? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

