/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artifactkeeper.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param events 
 * @param id 
 * @param isEnabled 
 * @param name 
 * @param url 
 * @param headers 
 * @param lastTriggeredAt 
 * @param repositoryId 
 */
@Serializable

data class WebhookResponse (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "events")
    val events: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_enabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "url")
    val url: kotlin.String,

    @Contextual @SerialName(value = "headers")
    val headers: kotlinx.serialization.json.JsonElement? = null,

    @Contextual @SerialName(value = "last_triggered_at")
    val lastTriggeredAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "repository_id")
    val repositoryId: java.util.UUID? = null

) {


}

